### ISSUE TITLE
Realizar la integracion para Ventas Contado

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#102]

**Comment by louvelaz** [comment]
@afaraldo 
- Cuando se hace una venta y se utiliza el crédito disponible de devoluciones de ese cliente para pagar completamente el monto total de la venta, sale un mensaje de error pero no dice cual es el error
  ![err](https://cloud.githubusercontent.com/assets/6853236/15798568/5edd122c-2a0a-11e6-9d77-649b22e79ddd.jpg)
- Se puede eliminar clientes, monedas, mercadería que tienen ventas asociadas y no debería
- En Editar: Cuando se quiere editar la venta, no aparecen los créditos disponibles de dicho cliente

**Comment by afaraldo** [comment]
@louvelaz con respecto al error "Se puede eliminar clientes, monedas, mercadería que tienen ventas asociadas y no debería", tenias razón con respecto que al borrar un cliente tiraba error de rails. Se debe a que no encontra el registro borrado.

Olvidamos agregar la opcion"-> { with_deleted }" a las relaciones, que permite que se obtengan objetos con eliminados con el borrado-ocioso. Agregaré eso para permitir listar las ventas (compras, detalles de boletas, cuyos clientes, monedas o mercaderias se han hayan borrado)
