### ISSUE TITLE
Actualizar el Dashboard

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#103]
​Actualizar la vista de bienvenida de forma a que presente datos resumidos y reales de la situación actual de la empresa. Los datos que debe presentar son:
- Cantidad de mercaderias actuales
- Saldo actual de la caja registradora en guaranies
- Total de cuentas a cobrar de clientes
- Total de cuentas a pagar a proveedores

También se requiere presentar mediante un gráfico la variación de las ventas y compras durante el mes actual.

![aaa](https://cloud.githubusercontent.com/assets/3639650/15549352/284471c0-227a-11e6-928e-b7e8152d6dd5.png)

**Comment by louvelaz** [comment]
@afaraldo 
- Se decidió que el gráfico de la variación de las ventas y compras sera de la semana actual, no del mes actual
- En los títulos "Cuentas a cobrar" y "Cuentas a pagar" no queda claro que los datos solo se obtienen de las ventas y compras a crédito.
