### ISSUE TITLE
Mejorar el formato de impresion

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#104]
Se requiere:
- Comprobar que una columna con contenido largo no debe las columnas desproporcionadas.
- Los saltos de pagina no deberia cortar una celda y las cabeceras de las tablas deben aparecer en cada pagina.
- Imprimir las boletas, recibos de dinero y notas (show de cada uno de ellos)

**Comment by louvelaz** [comment]
@mlored 
- No aparecen las cabeceras de las tablas en cada pagina 
- Los saltos de pagina no deberían cortar una celda, sin embargo la cortan 
- Imprimir el listado y el show en Devolución Venta tira error de rails

![err](https://cloud.githubusercontent.com/assets/6853236/15983375/deb09a46-2f73-11e6-9c34-f7121924b146.jpg)
![error](https://cloud.githubusercontent.com/assets/6853236/15983376/deb28f22-2f73-11e6-9053-fcf5ee8364c0.jpg)
![error2](https://cloud.githubusercontent.com/assets/6853236/15983377/deb4df5c-2f73-11e6-951e-1f57a9048c8f.jpg)

**Comment by bordonwork** [comment]
@mlored como vamos?

**Comment by mlored** [comment]
@bordonwork Tenia que hacer 3 correcciones de las cuales ya se soluciono lo del error en consola de rails para devoluciones en el show y en el listado.
Ahora estoy arreglando lo de las celdas que se cortan al imprimir cuando pasan a la pagina siguiente!

**Comment by mlored** [comment]
@louvelaz No aparecen las cabeceras de las tablas en cada pagina y Los saltos de pagina no cortan una celda en firefox y recomerdaremos usar firefox si se quiere imprimir.
