### ISSUE TITLE
Realizar las correcciones sugeridas por RBP

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#105]
Se requiere realizar los cambios sugeridos por la gema Rails Best Practices

**Comment by louvelaz** [comment]
@LudisM 
Queda pendiente la siguiente sugerencia:
![rbp](https://cloud.githubusercontent.com/assets/6853236/15845522/c33a0c14-2c41-11e6-8b45-9f1fa7b506c7.jpg)

**Comment by LudisM** [comment]
@louvelaz Esa sugerencia no se puede realizar ya que pide mover el código al modelo pero kaminari no tiene un model por lo cual ignoramos esta sugerencia.

**Comment by louvelaz** [comment]
@LudisM  Ok
