### ISSUE TITLE
Implementar el ABM de Mercaderias

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#15]
Requerimientos:
- El código de la mercadería no puede ser duplicado.
- El buscador debe buscar por nombre de mercadería o por el código. Tambien debe haber un filtro por categorias.
- Desde el formulario de mercadería se debe de poder crear una nueva categoria
- El listado debe tener paginación

Funcionalidades a desarrollar:
- [x] Crear mercadería
- [x] Editar mercadería
- [x] Eliminar mercadería (borrado ocioso)
- [x] Listar mercaderías
- [x] Buscador de mercaderías
  ![screenshot 2016-03-12 16 51 15](https://cloud.githubusercontent.com/assets/1580982/13730287/0f8663d4-e92a-11e5-8bdf-95653696a394.png)
  ![screenshot 2016-03-12 16 54 31](https://cloud.githubusercontent.com/assets/1580982/13730288/0fa0f938-e92a-11e5-8ad4-054de74aec4d.png)

**Comment by carlosleite** [comment]
@louvelaz url para testear: https://casa-de-las-pinturas-test.herokuapp.com/mercaderias

**Comment by louvelaz** [comment]
@carlosleite 
- Cuando se guarda una nueva categoría utilizando el botón +, no se puede desplazar el modal con la barra de desplazamiento, y los botones guardar y cancelar quedan inaccesibles.
- Hay mensajes que salen en ingles 

![bug sale en ingles](https://cloud.githubusercontent.com/assets/6853236/13770675/7eff55f2-ea67-11e5-8559-83f4f4395008.jpg)

![bug sale en ingles_2](https://cloud.githubusercontent.com/assets/6853236/13770677/89a72c8c-ea67-11e5-8d29-bf33f5da9bf5.jpg)
