### ISSUE TITLE
Implementar el ABM de Categorias de Mercaderias

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#16]
Requerimientos:
- El listado de categorias debe estar en la seccion de Mercaderias como indica una de las imagenes.
- El nombre de la categorias no puede ser duplicado.
- Las categorias pueden tener subcategorias y puede haber solos 2 niveles de profundidad: Categoria > Subcategoria. Una subcategoria no puede tener otras subcategorias.
- El buscador debe buscar por nombre de categoria.

Funcionalidades a desarrollar:
- [x] Crear categoria
- [x] Editar categoria
- [x] Eliminar categoria (borrado ocioso)
- [x] Listar categorias
- [x] Buscador de categorias

![screenshot 2016-03-12 16 30 20](https://cloud.githubusercontent.com/assets/1580982/13725271/ce628472-e87b-11e5-8586-96fadfcb0014.png)
![screenshot 2016-03-12 16 54 31](https://cloud.githubusercontent.com/assets/1580982/13725272/ce7f39a0-e87b-11e5-9081-5052f4db7f3d.png)

**Comment by carlosleite** [comment]
@louvelaz url para testear: https://casa-de-las-pinturas-test.herokuapp.com/mercaderias

**Comment by louvelaz** [comment]
@carlosleite Se pueden borrar Categorías ya usadas en Mercaderías.
