### ISSUE TITLE
Implementar la interfaz de configuracion del Sistema

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#18]

**Comment by carlosleite** [comment]
url para testear: https://casa-de-las-pinturas-test.herokuapp.com/configuraciones

**Comment by louvelaz** [comment]
@LudisM  
- Se mueve el formulario a medida que salen mensajes de error, pasa tanto en Chrome como en Firefox

![conf test 5 se mueve](https://cloud.githubusercontent.com/assets/6853236/13972716/0fa9c7f0-f07a-11e5-98a6-f6bcef411cb3.jpg)

![conf test 2](https://cloud.githubusercontent.com/assets/6853236/13972733/32e050d6-f07a-11e5-86b1-50f8b916643c.jpg)

![conf test 1](https://cloud.githubusercontent.com/assets/6853236/13975227/edc8b39a-f091-11e5-9a48-42cc3e145d3c.jpg)
- En el campo Email solo debería aceptar el formato  user@server.com
- El mensaje "Configuraciones actualizados correctamente" debería ser "Configuraciones actualizadas correctamente"

**Comment by louvelaz** [comment]
@LudisM El campo Email no parece tener limite superior
