### ISSUE TITLE
Implementar el ABM de Movimiento de Mercaderias

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#27]
Se requiere implementar las siguientes vistas:
- Listar Inventario
  ![image](https://cloud.githubusercontent.com/assets/3639650/13774596/8c488d5c-ea7e-11e5-9d84-f45116505b45.png)
- Nuevo Movimiento
  ![image](https://cloud.githubusercontent.com/assets/3639650/13774617/a502ff30-ea7e-11e5-89cf-6060fcde100e.png)

**Comment by carlosleite** [comment]
url para testear: https://casa-de-las-pinturas-test.herokuapp.com/movimiento_mercaderias

**Comment by carlosleite** [comment]
@louvelaz , ya testeaste algo de esto? Creo que seria mejor esperar que se definan las políticas y interfaces. Creo que va cambiar algo.

@bordonwork ?

**Comment by louvelaz** [comment]
@carlosleite Justo ahora estaba viendo este issue. Ok, voy a esperar que se definan las políticas e interfaces primero.

**Comment by bordonwork** [comment]
Bueno, seria mejor acabar ese issue considerando los requisitos anteriores,
de todas formas se puede agregar un issue en el sprint 4 para actualizar el
abm, a menos que consideres que el cambio tomaria mucho tiempo @carlosleite

**Comment by carlosleite** [comment]
No va llevar mucho tiempo. Ligeros cambios de UI y la validación de stock negativo (ahora no se permite y se va a permitir luego). Todo lo demás ya está.

**Comment by louvelaz** [comment]
@bordonwork Lo testeo entonces considerando los requisitos anteriores?

**Comment by bordonwork** [comment]
Si, seria importante testear con los requisitos previos

**Comment by louvelaz** [comment]
Ok.

**Comment by louvelaz** [comment]
@carlosleite 
- Se pueden guardar movimientos de fechas y años superiores al actual y no debería.
- Cuando se ingresa una cantidad mayor a 12 digitos, tira este error

![error](https://cloud.githubusercontent.com/assets/6853236/14095830/0b6fe540-f532-11e5-92cc-a21eb6042570.jpg)
- El botón cancelar no funciona

Sugerencias:
- Despues de dar clic en Guardar, en la interfaz que describe el nuevo movimiento, estaría bueno agregar un botón Listar, donde nuevamente se direccione a la interfaz Lista de Movimientos, porque no es intuitivo como volver a esa interfaz.

**Comment by carlosleite** [comment]
La sugerencia la vamos a definir al hacer el diseño de este ABM. Lo demás está solucionado
