### ISSUE TITLE
Implementar el ABM de Clientes

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#28]
Se requieren las siguientes vistas:
- Listar Clientes
  ![image](https://cloud.githubusercontent.com/assets/3639650/13774782/a1d678b8-ea7f-11e5-8e2f-1dabc6c4ddec.png)
- Nuevo/Editar Cliente
  ![image](https://cloud.githubusercontent.com/assets/3639650/13774799/b3fef5d8-ea7f-11e5-9751-faf671d94454.png)

**Comment by carlosleite** [comment]
url para testear: https://casa-de-las-pinturas-test.herokuapp.com/clientes

**Comment by louvelaz** [comment]
@mlored 
- Cuando en varios usuarios se utiliza el limite superior de longitud de varios campos, la grilla se desarregla y desaparecen los botones borrar y editar

![des](https://cloud.githubusercontent.com/assets/6853236/13976289/34c93e12-f09d-11e5-93a5-897ce727fb3d.jpg)
- Cuando se edita o borra un elemento que no esta en la primera pagina y se guarda, vuelve a la pagina 1 pero abajo en la barra de paginación muestra pagina 2, cuando debería mostrar pagina 1

**Comment by louvelaz** [comment]
@mlored Ahora cuando se edita o borra un elemento que no esta en la primera pagina, la barra de paginación deja de funcionar

**Comment by carlosleite** [comment]
@louvelaz Eso fue mi culpa. Ya esta solucionado.
Me olvidé de mencionar que los campos que pueden ser largos ahora se cortan y muestran de forma completa en un popover:
![screenshot 2016-03-28 11 15 29](https://cloud.githubusercontent.com/assets/1580982/14081111/fa40c7fe-f4d6-11e5-9fe5-9a42c6ed442e.png)

Y las tablas cuando no entran en la pantalla ahora tienen un scroll horizontal.

**Comment by louvelaz** [comment]
@carlosleite Si, me había fijado el popover y el scroll horizontal. Todo esta OK.
