### ISSUE TITLE
Implementar el layout de la aplicación

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#3]
Se requiere modificar el archivo [application.html.erb](https://github.com/rofaccess/CENADE/blob/master/code/app/views/layouts/application.html.erb) para que coincida con el diseño proveido
![image](https://cloud.githubusercontent.com/assets/3639650/13547220/53d2e630-e2a8-11e5-967f-b3dc426a7529.png)

La cual consta de dos elementos:
- Una barra de menú superior
- Un contenedor central en el cual se cargarán las vistas

**Comment by carlosleite** [comment]
Estos cambios se pueden ver en el branch development.
