### ISSUE TITLE
Implementar el ABM de Cotizacion

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#30]
Se requieren las siguientes vistas:
- Nueva Moneda
  ![image](https://cloud.githubusercontent.com/assets/3639650/13775151/b4974bd8-ea81-11e5-95b1-331a901a327b.png)
- Cotizaciones
  ![image](https://cloud.githubusercontent.com/assets/3639650/13775159/c76642b4-ea81-11e5-8199-ca8e5d9a5a08.png)

**Comment by afaraldo** [comment]
Durante el momento de la implementación se notó que el campo "moneda por defecto" no debería ser una opción configurable para el usuario, debido a que si el usuario cambia la moneda por defecto, todas las cotizaciones ingresadas anteriormente (monedas con su equivalente en "cotización") deberían actualizarse manualmente y esto crearía una inconsistencia.

**Comment by bordonwork** [comment]
Lo ideal sería que al cambiar la moneda por defecto las cotizaciones se
actualicen automaticamente a la nueva moneda...deberia haber una moneda
base, en este caso el guarani entonces:
1 guarani x pesos argentinos
1 guarani y reales brasileños
x'(pesos) = y'(reales a convertir) . x
                        ------------------------
                                          y

**Comment by carlosleite** [comment]
url: https://casa-de-las-pinturas-test.herokuapp.com/monedas

**Comment by louvelaz** [comment]
@afaraldo La cotización no debería aceptar 0, solo valores mayores
