### ISSUE TITLE
Documentar las Políticas de Usuarios

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#31]
Se deben agregar, actualizar y/o corregir las políticas de usuario concernientes al sistema en los siguientes aspectos:
### Superusuario
- Cuáles son las acciones que puede realizar?.
- Cuáles datos puede o no acceder/modificar/eliminar?.
- Cómo se controlan las acciones realizadas por éste?. Qué acciones se controlarán y cuáles no?.
- Se podrá o no cambiar la contraseña de este usuario?. En caso de que se pueda, cómo se restaurará la contraseña?.
- Se puede agregar/eliminar un superusuario?.
### Usuarios
- Quién los crea/modifica/elimina?.
- Se podrá eliminar un usuario?. En cuáles casos sí y en cuáles no?. Será un borrado físico u ocioso?.
- Podrá el usuario modificar su contraseña o no?. Si puede hacerlo, cómo se restaurará su contraseña?. Qué formato tendrá la contraseña?. Tendrá vencimiento la contraseña?.
- Cómo se controlan las acciones realizadas por éste?. Qué acciones se controlarán y cuáles no?.
### Roles
- Existen roles predefinidos?. Cuáles son?. A qué operaciones pueden o no acceder?. Qué acciones pueden o no realizar?. Especifique una matriz de roles.
- Existirán roles dinámicos?. De ser afirmativa la respuesta: cómo se crean dichos roles?. Quién/es los crea/an?. Se podrán asignar roles por acciones o por procesos o ambos?.
- Se podrán eliminar roles?. En cuáles casos sí y en cuáles no?. Será un borrado físico u ocioso?.
- Se podrá asignar más de un rol a un usuario?. Cómo se resuelven los conflictos entre dos o más roles asignados?. Especifique el flujo para resolver dichos conflictos.
### Sesión
- Podrá un usuario tener más de una sesión abierta?. 
- Tendrá la sesión un tiempo de expiración o no?.
### Importante
- Las preguntas formuladas en los apartados anteriores sirven de guía para redactar el documento. Éstas no pretenden limitar/excluir/agregar las políticas que el equipo considere o no necesarias.
- El formato de las políticas debe ir acorde al formato utilizado en las documentaciones ya existentes, sin embargo se recomienda utilizar un formato similar al proveído.
  ![image](https://cloud.githubusercontent.com/assets/3639650/13990758/4119f510-f0f4-11e5-8bd0-3aa13ba7a5a1.png)
- Cuando se tenga una versión del documento, éste debe ser referenciado (en formato de imagen, o un link al documento) en los comentarios de esta tarea a fin que puedan hacerse las recomendaciones, correcciones y preguntas pertinentes.

**Comment by afaraldo** [comment]
POLÍTICAS DE USUARIOS

ROLES
Existirán dos roles predefinidos, superusuario y administrador. Ambos pueden realizar todas las acciones dentro sistema. La diferencia está en que un administrador no puede crear, editar ni eliminar un superusuario.

USUARIOS

AGREGAR USUARIO
1.  Los usuarios pueden ser agregados al sistema por un usuario con rol de superusuario o rol administrador.
2.  No podrá existir dos usuarios con el mismo nombre de usuario.

EDITAR USUARIO
1.  Un usuario de rol superusuario o administrador, podrá editar los todos los datos y contraseñas de otros usuarios a través del formulario destinado a este fin. 
2.  Un usuario de cualquier rol puede modificar sus datos propios como nombre de usuario, su contraseña y otros datos. No podrá cambiar su rol.

ELIMINAR USUARIO
1.  Un usuario de rol superusuario o administrador, podrá eliminar a otros usuarios. 
2.  Un usuario de cualquier rol NO puede eliminarse a sí mismo.

CONTRASEÑAS
1.  Un usuario podrá modificar su propia contraseña. En caso de perderla deberá solicitar una nueva a un usuario administrador.
2.  Si la contraseña olvidada es la de un administrador, se deberá solicitar a otro usuario administrador o al soporte técnico.
3.  El formato de la contraseña requerirá ser de 8 caracteres como mínimo y 20 como máximo, deberá contener una letra mayúscula y una minúscula al menos.
4.  Las contraseñas no se deberá ser mostradas en ninguna parte, cuando se escriban deberan aparecer asteriscos. Esta se deberá confirmar contraseña en otro campo.
5.  Las constraseñas no poseen tiempo de validez.
 
SESIÓN
Un usuario solo podrá tener una sesión activa a la vez y la misma expirará luego de 30 minutos de inactividad.

REGISTRO DE AUDITORIA
Todas las acciones (crear, modificar, editar, eliminar) realizadas en el sistema se guardaran en un registro de auditoría incluyendo la fecha y el usuario correspondiente.
Obs.: Este registro de auditoría no será accesible ni visible desde el sistema.

ELIMINACION DE DATOS
La eliminación de un registro requerirá una confirmación del usuario a través de un mensaje de advertencia “¿Desea eliminar el {registro}?” con opciones de aceptar o cancelar.
El borrado de los registros será ocioso, es decir, no desapareceran de la base de datos.
