### ISSUE TITLE
Definir las políticas de Inventario

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#32]
Se deben agregar, actualizar y/o corregir las políticas de compras y ventas concernientes al sistema en los siguientes aspectos:
### Inventario
- Se permitirá stock negativo?. En cuáles casos y en cuáles no?.
- Existirán stocks mínimos, máximos o ambos?. Qué implicaciones deriva salir fuera de estos límites?.
- Se permitirá eliminar categorías asociadas a mercaderías?. En cuáles casos y en cuáles no?. Se realizará un borrado ocioso o físico?.
- Se permitirá eliminar mercaderías asociadas a ventas, compras, u otros documentos que genere el sistema?. En cuáles casos y en cuáles no?. Se realizará un borrado ocioso o físico?.
- Cómo se reflejará en el sistema movimientos de inventario que no son generados por ventas o compras?.
### Importante
- Las preguntas formuladas en el apartado anteriores sirven de guía para redactar el documento. Éstas no pretenden limitar/excluir/agregar las políticas que el equipo considere o no necesarias.
- El formato de las políticas debe ir acorde al formato utilizado en las documentaciones ya existentes, sin embargo se recomienda utilizar un formato similar al proveído.
  ![image](https://cloud.githubusercontent.com/assets/3639650/13990758/4119f510-f0f4-11e5-8bd0-3aa13ba7a5a1.png)
- Cuando se tenga una versión del documento, éste debe ser referenciado (en formato de imagen, o un link al documento) en los comentarios de esta tarea a fin que puedan hacerse las recomendaciones, correcciones y preguntas pertinentes.

**Comment by mlored** [comment]
### Políticas de Inventario

#### Del stock

• El stock no se podrá modificar desde el formulario de mercaderías.

#### Del stock negativo

• Se permitirá stock negativo con el conocimiento del usuario (cuando ocurra esté caso el usuario será advertido).

#### Del stock mínimo o máximo

• Existirán stocks mínimos.
• El stock mínimo se utilizará para advertir al usuario que se está quedando sin mercaderías.
• No existirán stocks máximos.

#### De las categorías

• Solo pueden existir 2 niveles de categorías, es decir la categoría padre puede tener una categoría hijo, pero un hijo no puede tener otro hijo.
• A una categoría que tiene hijos, no se le puede asignar una categoría padre.
• A una categoría padre no puede asignarse a sí mismo como categoría padre.
• No se puede asignar una categoría padre a una categoría que se hija.

#### De las categorías asociadas a mercaderías

• Se permitirá eliminar categorías asociadas a mercaderías en el caso que la categoría no tenga asociada ninguna mercadería activa, es decir que no esté eliminada.
• Se realizará borrado ocioso.

#### De las mercaderías

• El código de la mercadería debe ser único.
• Si el precio de costo de una mercadería comprada recientemente es mayor al precio de costo de la mercadería que se tiene en stock, el mismo será el nuevo costo.
• Si el precio de costo de la mercadería comprada recientemente es menor al precio de costo de la mercadería que se tiene en stock, se actualizará el mismo a un precio promedio ponderado.

#### De los movimientos de mercaderías

• La fecha del movimiento no puede superar la fecha actual, es decir no puede ser una fecha futura.

#### De las mercadería asociada a venta, compra u otros documentos que genere el sistema

• No se puede eliminar si la mercadería está asociada a compra o ventas pendientes.
• Se realizará un borrado ocioso.

#### De los movimientos de inventario que no son generados por ventas o compras

• Los movimientos de inventario que no son generados por ventas o compras, en el sistema se reflejará por medio de un ABM de Movimientos de Mercaderías que sería de ingreso o de egreso.

**Comment by LudisM** [comment]
En este punto: No tendría implicancias mayores en el caso de salir fuera de estos límites, solo la de advertencia. 
A que limites  se refiere?

**Comment by mlored** [comment]
Cambiaré ese punto debido a que no manejamos stock máximo, es decir no tendremos límite máximo

**Comment by mlored** [comment]
Actualice las políticas agregando algunas de las categorías y de las mercaderías

**Comment by carlosleite** [comment]
Creo que falta políticas de movimientos de mercaderías.

**Comment by afaraldo** [comment]
Creo que falta definir como las compras afectan (o actualizan) el precio de costo de las mercaderias. Ejemplo: existe en stock una mercaderia x a precio de costo 5.000. Cuando se compra el mismo producto a un precio de 6.000. cual es el valor del precio de costo de la mercaderia en cuestion?

**Comment by afaraldo** [comment]
Salvo la observación anterior. Creo que las demás políticas estan bien. :+1: Y si hay conformidad se puede cerrar el ticket.

**Comment by carlosleite** [comment]
Tambien falta la politica que el stock no se podrá modificar desde el formulario de mercaderia. 
Creo que deberia ir aca.

**Comment by mlored** [comment]
Agregue las siguiente políticas:
De las mercaderías
• El código de la mercadería debe ser único.
• Si el precio de costo de una mercadería comprada recientemente es mayor al precio de costo de la mercadería que se tiene en stock, el mismo será el nuevo costo.
• Si el precio de costo de la mercadería comprada recientemente es menor al precio de costo de la mercadería que se tiene en stock, se actualizará el mismo a un precio promedio ponderado.
De los movimientos de mercaderías
• La fecha del movimiento no puede superar la fecha actual, es decir no puede ser una fecha futura.

**Comment by mlored** [comment]
### Políticas de Inventario

#### Del stock

• El stock no se podrá modificar desde el formulario de mercaderías.

#### Del stock negativo

• Se permitirá stock negativo con el conocimiento del usuario (cuando ocurra esté caso el usuario será advertido).

#### Del stock mínimo o máximo

• Existirán stocks mínimos.
• El stock mínimo se utilizará para advertir al usuario que se está quedando sin mercaderías.
• No existirán stocks máximos.

#### De las categorías

• Solo pueden existir 2 niveles de categorías, es decir la categoría padre puede tener una categoría hijo, pero un hijo no puede tener otro hijo.
• A una categoría que tiene hijos, no se le puede asignar una categoría padre.
• A una categoría padre no puede asignarse a sí mismo como categoría padre.
• No se puede asignar una categoría padre a una categoría que se hija.

#### De las categorías asociadas a mercaderías

• Se permitirá eliminar categorías asociadas a mercaderías en el caso que la categoría no tenga asociada ninguna mercadería activa, es decir que no esté eliminada.
• Se realizará borrado ocioso.

#### De las mercaderías

• El código de la mercadería debe ser único.
• Si el precio de costo de una mercadería comprada recientemente es mayor al precio de costo de la mercadería que se tiene en stock, el mismo será el nuevo costo.
• Si el precio de costo de la mercadería comprada recientemente es menor al precio de costo de la mercadería que se tiene en stock, se actualizará el mismo a un precio promedio ponderado.

#### De los movimientos de mercaderías

• La fecha del movimiento no puede superar la fecha actual, es decir no puede ser una fecha futura.

#### De las mercadería asociada a venta, compra u otros documentos que genere el sistema

• No se puede eliminar si la mercadería está asociada a compra o ventas pendientes.
• Se realizará un borrado ocioso.

#### De los movimientos de inventario que no son generados por ventas o compras

• Los movimientos de inventario que no son generados por ventas o compras, en el sistema se reflejará por medio de un ABM de Movimientos de Mercaderías que sería de ingreso o de egreso.
