### ISSUE TITLE
Definir las políticas de Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#33]
Se deben agregar, actualizar y/o corregir las políticas de ventas concernientes al sistema en los siguientes aspectos:
### Ventas
- Se pueden hacer ventas de mercaderías que no posean stock en el sistema?. En cuáles casos y en cuáles no?. 
- Se podrán hacer ventas a créditos?. Qué criterios se seguirán al respecto?. Cómo se controlarán las cobros?. Qué documentos intervienen?.
- Se podrán anular las ventas?. En cuáles casos y en cuáles no?. Qué ocurre con el inventario?.
- Los cobros se podrán realizar con distintos tipos de pagos?. Con cuáles?.
### Devoluciones
- Se podrán realizar devoluciones o cambios de mercaderías?. En cuáles casos y en cuáles no?. Cómo se registrará dicho proceso?.
- Se podrán realizar devoluciones de dinero?. En cuáles casos y en cuáles no?. Cómo se registrará dicho proceso?.
### Importante
- Las preguntas formuladas en los apartados anteriores sirven de guía para redactar el documento. Éstas no pretenden limitar/excluir/agregar las políticas que el equipo considere o no necesarias.
- El formato de las políticas debe ir acorde al formato utilizado en las documentaciones ya existentes, sin embargo se recomienda utilizar un formato similar al proveído.
  ![image](https://cloud.githubusercontent.com/assets/3639650/13990758/4119f510-f0f4-11e5-8bd0-3aa13ba7a5a1.png)
- Cuando se tenga una versión del documento, éste debe ser referenciado (en formato de imagen, o un link al documento) en los comentarios de esta tarea a fin que puedan hacerse las recomendaciones, correcciones y preguntas pertinentes.

**Comment by LudisM** [comment]
Políticas de Ventas
Ventas
• Se podrán vender mercaderías que no posean stock en el sistema, si esto ocurre antes de guardar se debe verificar que la carga no cause un stock negativo, y si es así hay que notificar al usuario y da la  opción de continuar o cancelar.
• Se podrán realizar ventas a crédito solo a los clientes que tengan un límite de crédito disponible.
• Los cobros de ventas a crédito  se controlaran  con fechas de vencimientos y tendrá una sola fecha de vencimiento.
• Los cobros  de ventas a crédito se podrán realizar en cobros parciales y en distintas formas de cobros (efectivo y tarjeta).
• Las ventas al contado se pueden editar y/o eliminar.
• Las ventas a crédito solo se puede editar y/o eliminar si no tiene cobros asociados.
• Se debe actualizar el inventario de acuerdo a las acciones realizas (editar o eliminar venta).
• Para los cobros se podrán aceptar 2 formas de cobros que son efectivo y tarjeta de crédito
•       Para los cobros se aceptan diferentes monedas : Guarani, peso, dolar y real.
Devoluciones
• Siempre se podrá hacer una devolución ya sea a contado o crédito, al registrar la devolución se tendrá que relacionar con una sola venta.
•       Cuando se quiera hacer un cambio se realiza una devolución y se registra una nueva venta
• No se realizan devoluciones de dinero.

**Comment by bordonwork** [comment]
Con respecto a las devoluciones que ocurre si el cliente quiere hacer una
devolución o cambio y no hay mercadería para hacer dicho cambio?...

**Comment by LudisM** [comment]
Solo se realiza una devolución es un error mio cambios no se hace.
si quiere hacer un cambio se tiene que hacer una devolución y registrar una nueva venta, y en caso que de que no haya mercadería para el cambio el usuario decide si realiza o no la devolución.

**Comment by bordonwork** [comment]
Estoy confundido. Qué es una devolución y qué es un cambio, desde el punto
de vista del negocio?

**Comment by LudisM** [comment]
Para realizar un cambio de mercadería se realiza mediante una devolución, entonces yo realizo la devolución de mercadería que trae el cliente y se realiza una venta de lo que quiere llevar a cambio, me explico?

**Comment by bordonwork** [comment]
Entiendo, no habria nota de debito entonces para anular la factura?

**Comment by LudisM** [comment]
No no habra nota de debito, en el caso que quiera anular se elimina directamente la venta.

**Comment by bordonwork** [comment]
@afocampos su opinion?

**Comment by LudisM** [comment]
La empresa no emite nota de débito ni crédito.

**Comment by bordonwork** [comment]
Pero la venta se debería poder anular de alguna forma al hacer una
devolucion porque sino habrá un doble ingreso de caja

**Comment by afaraldo** [comment]
• Se debe actualizar el inventario de acuerdo a las acciones realizas (**crear,** editar o eliminar venta). :)

Con respecto al comentario anterior de devolución de mercaderias, no existirá doble ingreso en caja porque la segunda venta (entienda se como el cambio de mercadería) será una venta que se pagará con el crédito a favor del cliente (generado por la devolución). En terminos generales la devolución de mercadería actua como una nota de débito, sin embargo el negocio no utiliza tal formalismo e incluirlo en el sistema sería contraproducente para el cliente, porque no es la forma en la que realiza los trabajos.

**Comment by afaraldo** [comment]
Quizás no se entendio esa parte porque creo que falta escribirla en la parte de devoluciones.
Sería: 
Devoluciones:
- Toda devolución tendrá un campo "total_importe", correspondiente a la suma de los precios de cada producto. El valor de este campo se le sumará al saldo del cliente a través de un movimiento en la cuenta corriente del mismo. Algo así, creo.

**Comment by afaraldo** [comment]
- Siempre se podrá hacer una devolución ya sea **de una venta** a contado o crédito, al registrar la devolución se tendrá que relacionar con una sola venta.

Con todo lo demás estoy de acuerdo. Y si no hay más que agregar, creo que podemos dar por cerrado el ticket

**Comment by carlosleite** [comment]
Falta agregar las políticas de que no serán permitidas fechas futuras para el campo :fecha de ventas, cobros, y devoluciones.

**Comment by LudisM** [comment]
### Políticas de Ventas

#### Ventas

• Se podrán vender mercaderías que no posean stock en el sistema, si esto ocurre antes de guardar se debe verificar que la carga no cause un stock negativo, y si es así hay que notificar al usuario y da la  opción de continuar o cancelar.
• Se podrán realizar ventas a crédito solo a los clientes que tengan un límite de crédito disponible.
• Los cobros de ventas a crédito  se controlaran  con fechas de vencimientos y tendrá una sola fecha de vencimiento.
• Los cobros  de ventas a crédito se podrán realizar en cobros parciales y en distintas formas de cobros (efectivo y tarjeta).
• Las ventas al contado se pueden editar y/o eliminar.
• Las ventas a crédito solo se puede editar y/o eliminar si no tiene cobros asociados.
• Se debe actualizar el inventario de acuerdo a las acciones realizas (editar o eliminar venta).
• Para los cobros se podrán aceptar 2 formas de cobros que son efectivo y tarjeta de crédito
•   Para los cobros se aceptan diferentes monedas : Guarani, peso, dolar y real.
• no serán permitidas fechas futuras para el campo :fecha de ventas, cobros, y devoluciones.

#### Devoluciones

• Siempre se podrá hacer una devolución ya sea una venta contado o crédito, al registrar la devolución se tendrá que relacionar con una sola venta.
•     Toda devolución tendrá un campo "total_importe", correspondiente a la suma de los precios de cada producto. El valor de este campo se le sumará al saldo del cliente a través de un movimiento en la cuenta corriente del mismo.
•   Cuando se quiera hacer un cambio se realiza una devolución, se registra una nueva venta y para cobrar se selecciona el credito del cliente.
• No se realizan devoluciones de dinero.

**Comment by LudisM** [comment]
@afaraldo  @carlosleite  @mlored ya agregue algunas políticas que me sugirieron pueden echarle un vistazoasi poder cerrar la tarea
