### ISSUE TITLE
Definir las políticas de Compras y Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#34]
Se deben agregar, actualizar y/o corregir las políticas de gastos concernientes al sistema en los siguientes aspectos:
### Compras y Gastos
- Qué documentaciones se requieren para registrar compras de mercaderías o gastos?.
- Se podrán hacer compras a créditos?. Qué criterios se seguirán al respecto?. Cómo se controlarán los pagos?. Qué documentos intervienen?.
- Se podrán anular las compras y gastos?. En cuáles casos y en cuáles no?. Qué ocurre con el inventario en las compras?.
- Los pagos se podrán realizar con distintos tipos de pagos?. Con cuáles?.
### Devoluciones
- Se podrán realizar devoluciones o cambios de mercaderías?. En cuáles casos y en cuáles no?. Cómo se registrará dicho proceso?.
- Se podrá registrar créditos en compras?. En cuáles casos y en cuáles no?. Cómo se registrará dicho proceso?.
### Importante
- Las preguntas formuladas en los apartados anteriores sirven de guía para redactar el documento. Éstas no pretenden limitar/excluir/agregar las políticas que el equipo considere o no necesarias.
- El formato de las políticas debe ir acorde al formato utilizado en las documentaciones ya existentes, sin embargo se recomienda utilizar un formato similar al proveído.
  ![image](https://cloud.githubusercontent.com/assets/3639650/13990758/4119f510-f0f4-11e5-8bd0-3aa13ba7a5a1.png)
- Cuando se tenga una versión del documento, éste debe ser referenciado (en formato de imagen, o un link al documento) en los comentarios de esta tarea a fin que puedan hacerse las recomendaciones, correcciones y preguntas pertinentes.

**Comment by carlosleite** [comment]
### Compra de mercaderías

#### Políticas:
1. Las compras pueden ser al contado o a crédito
   1. Si es al contado:
      1. Los datos del pago se indican al cargar la compra.
   2. Si es a credito:
      1. El total de la compra debe ser menor o igual al crédito disponible del proveedor. Se podrá modificar el limite de crédito desde el formulario de compra.
      2. Luego de guardar la compra se debe actualizar los movimientos de cuenta corriente del proveedor y la linea de crédito.
2. Luego de guardar la compra las cantidades de los detalles se deben reflejar en los movimientos de mercaderías.
3. Al editar o eliminar una compra: estas operaciones pueden provocar stock negativo con conocimiento del usuario.
4. Política de edición/eliminación de compras: 
   1. Una compra al contado se podrá editar o eliminar. Se deben actualizar las diferencias de cantidades y montos de pagos involucrados.
   2. Una compra a crédito SOLO se podrá editar o eliminar si es que todavía no tiene pagos asociados.
5. Al cargar las compras se podrá seleccionar créditos a favor provenientes de devolución de mercaderías.
6. La fecha de las compras no podrá ser una fecha futura.

### Devolución de mercaderías de compras

Las devoluciones de mercaderías se utilizan para los casos donde se devuelven mercaderias a los proveedores. Se produce un movimiento de inventario y un saldo a favor con el proveedor. No se devuelve dinero a caja en ningun caso.

#### Políticas:
1. El total de la devolución es un crédito a favor que la empresa tendrá con el proveedor seleccionado.
2. La creación o modificación de las devoluciones puede provocar stock negativo con conocimiento del usuario.
3. Política de edición y eliminación de devoluciones: SOLO se podrá editar y eliminar la devolución si el crédito de la misma no ha sido utilizado. Se deben reflejar las diferencias de los créditos y cantidades de mercaderías de la misma.
4. La fecha de las devoluciones no podrá ser una fecha futura.

### Pagos

#### Políticas:
1. Se deberá poder realizar pagos de compras pendientes. 
2. Las formas de pago puede ser solo Efectivo. Se puede seleccionar las diferentes monedas disponibles en el sistema.
3. Antes de guardar se debe comprobar que el monto a sacar de caja este disponible en la misma. Si no hay suficiente dinero en caja según el sistema se debe advertir al usuario que  no hay suficiente dinero registrado y dar la opción de continuar de todos modos o cancelar la carga.
4. El formulario deberá tener una forma de asociar créditos disponibles con el proveedor (que se generan con las devoluciones de mercaderías).
   1. El total de los créditos de devoluciones seleccionados debe ser igual o menor al total de las facturas seleccionadas. Si es mayor el usuario puede seleccionar el monto a usar de los créditos seleccionados.
5. Luego de guardar la compra los movimientos del pago quedan reflejados en los movimientos de caja.
6. Si se seleccionó créditos de devoluciones, el crédito de los mismos se debe actualizar.
7. Se deben actualizar la cuenta corriente y saldo del proveedor.
8. Siempre se podrá editar y eliminar los pagos.
9. La fecha de los pagos no podrá ser una fecha futura.

### Gastos y Movimientos de caja

Son los gastos varios de la empresa como servicios varios, combustible, sueldos, etc. se registraran a travez de los movimientos de caja. Se utilizaran categorías de gastos para clasificar luego estos gastos en un reporte

#### Políticas:
1. Los movimientos pueden ser de ingreso o egreso
2. Cuando el movimiento de caja es de tipo :egreso se podrá seleccionar  una categoría de gasto (opcional).
3. La carga, edición o eliminación de un movimiento se debe reflejar en el extracto de caja.
4. Siempre se podrá editar o eliminar movimientos.
5. Una categoría no se podrá eliminar si está referenciada en algún movimiento.
6. La fecha de los movimientos de caja no podrá ser una fecha futura.

**Comment by afaraldo** [comment]
Con respecto a la sección de Movimiento de Cajas y Gastos.
Politicas:
2. Cuando el movimiento de caja es de tipo :egreso se debe seleccionar una categoría de gasto.

Creo que seria mejor decir que... "Cuando el movimiento de caja es del tipo :egreso se **puede** seleccionar una categoria de gasto." ya que el mismo no es obligatorio, en mi opinión.

**Comment by afaraldo** [comment]
Todo lo demás me parece correcto y listo para cerrar el ticket. :+1:

**Comment by carlosleite** [comment]
Tiene sentido. :+1:

**Comment by carlosleite** [comment]
Actualizado

**Comment by carlosleite** [comment]
Actualizado políticas de fechas futuras.
