### ISSUE TITLE
Definir la documentación para el feature Compras

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#35]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by carlosleite** [comment]
### Descripción

El feature compra es utilizado para realizar las compra de mercaderías a contado o crédito a un proveedor. Se generan movimientos de mercaderías y cuentas corrientes

#### Actores

usuario y cliente.

#### Vistas
1. Listar
2. Crear
3. Editar

### Flujos

#### Nueva Compra al contado
1. Se selecciona la opcion de Nueva compra
2. Se rellena los campos de la cabecera
3. Se agregan las mercaderias correspondientes a la compra
   1. Se podrá crear una nueva mercadería desde el formulario
4. Se debe mostrar una seccion donde se pueda ingresar las formas de pago
5. Se podrá seleccionar créditos disponible de devoluciones al proveedor
   1. Las devoluciones seleccionadas deben ser del proveedor seleccionado
   2. El total de crédito seleccionado no puede ser mayor al total de las mercaderías seleccionadas
   3. Si se seleccionó créditos de devoluciones, el crédito usado de los mismos se debe actualizar.
6. El total de la compra es igual a el total de las mercaderías menos el crédito seleccionado.
7. El total de los detalles del pago debe ser igual al total de la compra
8. El usuario confirma la compra.
9. El sistema guarda la compra e informa al usuario que se registró la compra.
10. Luego de guardar la compra las cantidades de los detalles se deben reflejar en los movimientos de mercaderías.

##### Excepciones
1. Si el total de crédito seleccionado es mayor al total de mercaderías no se debe guardar la compra.
   1. Se debe dar la opcion al usuario de ingresar el monto a usar de los creditos.

#### Nueva Compra a crédito
1. Se selecciona la opcion de Nueva compra
2. Se rellena los campos de la cabecera
3. Se agregan las mercaderias correspondientes a la compra
   1. Se podrá crear una nueva mercadería desde el formulario
4. Se debe mostrar un mensaje indicando el credito disponible con el proveedor.
5. El total de la compra es igual a el total de las mercaderías menos el crédito seleccionado.
6. El usuario confirma la compra.
7. El sistema guarda la compra e informa al usuario que se registró la compra.
8. Luego de guardar la compra se debe actualizar los movimientos de cuenta corriente del proveedor y la linea de crédito.
9. Luego de guardar la compra las cantidades de los detalles se deben reflejar en los movimientos de mercaderías.

##### Excepciones
1. Si el crédito disponible del proveedor es inferior al total de la compra no se debe permitir guardar la compra
   1. Si la linea disponible no es suficiente se debe advertir al usuario y se debe dar la opción de modificar el limite de crédito del proveedor o cancelar la carga de la compra.

#### Editar Compra contado
1. El usuario solicita editar una compra realizada al contado.
2. El sistema muestra el formulario con los datos de la compra.
3. El usuario modifica los campos que desea modificar, excepto la condición de compra que no podrá ser modificado.
4. El usuario confirma la edición.
5. Se debe verificar si las cantidades introducidas puede causar existencia negativa.
6. Se deben hacer las actualizaciones de stock necesarias en caso de que se haya modificado alguna de las cantidades.
7. El sistema guarda la edición e informa al usuario que se registró la edición.

##### Excepciones
1. Si las modificaciones de cantidades pueden causar stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la modificacion de la compra.

#### Editar venta a crédito
1. El usuario solicita editar una compra realizada a crédito.
2. El sistema muestra el formulario con los datos de la compra.
3. El usuario modifica los campos que desea modificar, excepto la condición de compra que no podrá ser modificado.
4. El usuario confirma la edición.
5. Se debe verificar si las cantidades introducidas puede causar existencia negativa.
6. El sistema guarda la edición e informa al usuario que se registró la edición.
7. Se deben hacer las actualizaciones de stock necesarias en caso de que se haya modificado alguna de las cantidades.
8. Se debe actualizar el saldo de la cuenta corriente correspondiente de ser necesaria

##### Excepciones
1. Si las modificaciones de cantidades pueden causar stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la modificacion de la compra.
2. Si se modificó el total de la compra y esta diferencia es mayor al credito disponible del proveedor no debe permitir guardar.
   1. Se debe dar la opción de modificar el limite de crédito del proveedor o cancelar la modificacion de la compra.

#### Listar ventas
1.  Se debe entrar en la opción de compras.
2.  Se muestran las ultimas 25 compras realizadas.
3.  Además se muestra la opción para filtrar por fechas, por número, por estado, por condición y por proveedor.
4.  El usuario puede aplicar los filtros deseados.
5.  El sistema muestra el listado con los filtros aplicados.
6.  Debe haber un boton con la opción de imprimir el listado.
   1. Este boton debe levantar la ventana de impresion del navegador con el listado.

### Dependencias
1.  ABM Mercaderias.
2.  ABM Proveedores.
3.  ABM Pagos.
4.  Cuentas Corrientes.

### Gemas necesarias
1.  Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Enumerize
   - Version: '~> 0.11.0'
   - Utilización: para utilizar enums en los modelos.
4.  Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
5.  Paranoia
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.
6.  Cocoon
   - Version: '~> 1.2.8'
   - Utilización: para formularios anidados dinámicos del lado del cliente.

**Observación:** notese el operador pesimista(~>) para evitar que se incluyan cambios mayores de las gemas si en algun momento se hace un update. Estos son los que se usan ahora; puede cambiar en el futuro por diferentes razones(fixes,  mejoras, nuevos features, etc. en las gemas)

### Prioridad

10

### Mensajes

_Posible stock negativo:_ "La operación va a provocar existencia negativa en los siguientes productos: %{productos}. Esta seguro que quiere continuar? [Continuar] | [Cancelar]"
_Saldo insuficiente de proveedor:_ "El proveedor %{nombre} no posee saldo suficiente para realizar la operación."

_Creación exitosa:_ "Se ha guardado la compra exitosamente"
_Creación fallida:_ "Ha ocurrido un problema al tratar de guardar la compra. %{errores}"
_Actualización exitosa:_ "Se ha actualizado la compra exitosamente"
_Actualización fallida:_ "Ha ocurrido un problema al tratar de actualizar la compra. %{errores}"
_Eliminación exitosa:_ "Se ha eliminado la compra exitosamente"
_Eliminación fallida:_ "Ha ocurrido un problema al tratar de eliminar la compra. %{errores}"

**Comment by bordonwork** [comment]
@carlosleite podrías agregar la versión de las gemas y la función de cada una.

**Comment by carlosleite** [comment]
Claro. Lo voy a hacer.

**Comment by carlosleite** [comment]
Actualizado sección de Gemas y Mensajes
