### ISSUE TITLE
Definir la documentación para el feature Pedido de Compra

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#36]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by carlosleite** [comment]
Teniendo en cuenta el tiempo de desarrollo bastante ajustado planeamos eliminar este feature ya que no es imprescindible para el negocio.

**Comment by bordonwork** [comment]
@carlosleite porque reabriste este issue?

**Comment by bordonwork** [comment]
@carlosleite perdón, lo cerré por error

**Comment by carlosleite** [comment]
@bordonwork , no estaba seguro donde debia ponerlo. Porque queria comentarles el caso de este issue en clase antes de cerrarlo.

**Comment by bordonwork** [comment]
@carlosleite mejor que quede como cerrado puesto que para las 3 el sprint
ya debe estar cerrado

2016-04-05 12:25 GMT-03:00 carlosleite notifications@github.com:

**Comment by carlosleite** [comment]
Sip. Fue un lapso de confusión. Hace un rato lo cerré de nuevo.
