### ISSUE TITLE
Definir la documentación para el feature Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#37]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by LudisM** [comment]
### Descripción

El feature venta es utilizado para realizar las ventas de mercaderías a contado o crédito a un cliente, si la venta es al contado se realiza el cobro de la venta y si la venta es a crédito el sistema muestra una ventana para ingresar la fecha de vencimiento del cobro e informa el límite de crédito que posee el cliente.

##### Actores

usuario y cliente.

#### Vistas necesarias

• Vista nuevo: Es un formulario para crear una nueva venta.
• Vista editar: Es un formulario que permite editar una.
• Vista listar: Lista todas las ventas realizadas hasta el momento.
En la vista listar tendrá un botón x que sirve para eliminar una venta.

### Flujos

#### Nueva venta contado

##### Flujo
1.  El Usuario solicita al sistema comenzar el proceso de registro de una nueva venta.
2.  El sistema muestra el formulario y solicita los datos al usuario.
3.  El usuario ingresa las mercaderías que se está vendiendo.
4.  El sistema muestra el monto total de la venta.
5.  El sistema solicita al usuario los datos del cobro.
6.  El usuario ingresa las formas de pago y monedas con los montos.
7.  El usuario cierra la venta.
8.  El sistema guarda la venta, el cobro, actualiza el inventario e informa al usuario que se registró la venta y pago.

#### Nueva venta crédito

##### Flujo
1.  El usuario solicita al sistema comenzar el proceso de registro de una nueva venta.
2.  El sistema solicita los datos al usuario.
3.  El usuario selecciona el cliente.
4.  El usuario ingresa las mercaderías que se está vendiendo.
5.  El sistema muestra el monto total de la venta.
6.  El sistema verifica que la línea de crédito disponible del cliente seleccionado sea suficiente para la venta.
7.  El usuario confirma la venta.
8.  El sistema guarda la venta, actualiza el inventario e informa al usuario que se registró la venta.

##### Excepciones
1.  Si el crédito disponible del cliente no es suficiente el sistema advierte al Usuario.

#### Editar venta contado

##### Flujo
1.  El usuario solicita editar una venta  realizada.
2.  El sistema muestra el formulario con los datos de la venta.
3.  El usuario modifica los campos que desea modificar, excepto la condición de venta que no podrá ser modificado.
4.  El usuario confirma la edición.
5.  El sistema guarda la edición, actualiza el inventario e informa al usuario que se registró la edición.

#### Editar venta a crédito

##### Flujo
1.  El usuario solicita editar una venta  realizada de la cuenta de un cliente.
2.  El sistema muestra el formulario con los datos de la venta.
3.  El usuario modifica los campos que desea modificar, excepto la condición de venta que no podrá ser modificado.
4.  El usuario confirma la edición.
5.  El sistema guarda la edición, actualiza el inventario, actualiza el crédito del cliente e informa al usuario que se registró la edición.

##### Excepciones
1.  Si el crédito disponible del cliente no es suficiente el sistema advierte al Usuario.

#### Listar ventas

##### Flujo
1.  Se debe entrar en la opción de ventas
2.  Se muestran las ultimas 25 ventas realizadas ya se a crédito y contado.
3.  Además se muestra la opción para filtrar por fechas, por número, por estado, por condición y por cliente.
4.  El usuario puede aplicar los filtros deseados.
5.  El sistema muestra el listado con los filtros aplicados.
6.  Se cuenta también con la opción de imprimir.

### Dependencias

Entre las dependencias tenemos:
1.  ABM Mercaderias.
2.  ABM Clientes.
3.  ABM Cobros.
4.  ABM Cuentas Corrientes.

### Gemas necesarias
1.  Ransack
2.  Kaminari 
3.  Enumerize
4.  Simple_form
5.  Paranoia.
6.  Cocoon

### Prioridad

10
.

**Comment by carlosleite** [comment]
@LudisM 
Falta el paso donde se controla el stock al crear y editar la venta: "Si las modificaciones de cantidades pueden causar stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la operación".

También los mensajes.

**Comment by LudisM** [comment]
### Descripción

El feature venta es utilizado para realizar las ventas de mercaderías a contado o crédito a un cliente, si la venta es al contado se realiza el cobro de la venta y si la venta es a crédito el sistema muestra una ventana para ingresar la fecha de vencimiento del cobro e informa el límite de crédito que posee el cliente.

#### Actores

usuario y cliente.

#### Vistas necesarias

• Nuevo.
• Editar
• Listar

### Flujos

#### Nueva venta contado

##### Flujo
1. El Usuario solicita al sistema comenzar el proceso de registro de una nueva venta.
2. El sistema muestra el formulario y solicita los datos al usuario.
3. El usuario ingresa las mercaderías que se está vendiendo.
4. Si las cantidades de mercaderias que se estan vendiendo causa stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la operación.
5. El sistema muestra el monto total de la venta.
6. El sistema solicita al usuario los datos del cobro.
7. El usuario ingresa las formas de pago y monedas con los montos.
8. El usuario cierra la venta.
9. El sistema guarda la venta, el cobro, actualiza el inventario e informa al usuario que se registró la venta y pago.

#### Nueva venta crédito

##### Flujo
1. El usuario solicita al sistema comenzar el proceso de registro de una nueva venta.
2. El sistema solicita los datos al usuario.
3. El usuario selecciona el cliente.
4. El usuario ingresa las mercaderías que se está vendiendo.
5. Si las cantidades de mercaderias que se estan vendiendo causa stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la operación.
6. El sistema muestra el monto total de la venta.
7. El sistema verifica que la línea de crédito disponible del cliente seleccionado sea suficiente para la venta.
8. El usuario confirma la venta.
9. El sistema guarda la venta, actualiza el inventario e informa al usuario que se registró la venta.

##### Excepciones
1. Si el crédito disponible del cliente no es suficiente el sistema advierte al Usuario.

#### Editar venta contado

##### Flujo
1. El usuario solicita editar una venta realizada.
2. El sistema muestra el formulario con los datos de la venta.
3. El usuario modifica los campos que desea modificar, excepto la condición de venta que no podrá ser modificado.
4. Si las modificaciones de cantidades pueden causar stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la operación
5. El usuario confirma la edición.
6. El sistema guarda la edición, actualiza el inventario e informa al usuario que se registró la edición.

#### Editar venta a crédito

##### Flujo
1. El usuario solicita editar una venta realizada de la cuenta de un cliente.
2. El sistema muestra el formulario con los datos de la venta.
3. El usuario modifica los campos que desea modificar, excepto la condición de venta que no podrá ser modificado.
4. Si las modificaciones de cantidades pueden causar stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la operación
5. El usuario confirma la edición.
6. El sistema guarda la edición, actualiza el inventario, actualiza el crédito del cliente e informa al usuario que se registró la edición.

##### Excepciones
1. Si el crédito disponible del cliente no es suficiente el sistema advierte al Usuario.

#### Listar ventas

##### Flujo
1. Se debe entrar en la opción de ventas
2. Se muestran las ultimas 25 ventas realizadas ya se a crédito y contado.
3. Además se muestra la opción para filtrar por fechas, por número, por estado, por condición y por cliente.
4. El usuario puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.
6. Se cuenta también con la opción de imprimir.

#### Eliminar venta
1. Desde el listado de ventas el usuario debe seleccionar la opción de eliminar.
2. El usuario debe confirmar el borrado.

### Dependencias

Entre las dependencias tenemos:
1. ABM Mercaderias.
2. ABM Clientes.
3. ABM Cobros.
4. ABM Cuentas Corrientes.

### Gemas necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.v
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Enumerize
   - Version: '~> 0.11.0'
   - Utilización: para utilizar enums en los modelos.
4. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
5. Paranoia.
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.
6. Cocoon
   - Version: '~> 1.2.8'
   - Utilización: para formularios anidados dinámicos del lado del cliente.

### Prioridad

10

### Mensajes
- Posible stock negativo: "La operación va a provocar existencia negativa en los siguientes productos: %{productos}. Esta seguro que quiere continuar? [Continuar] | [Cancelar]"
  Saldo insuficiente de clienter: "El cliente %{nombre} no posee saldo suficiente para realizar la operación."
- Creación exitosa: "Se ha guardado la venta exitosamente"
- Creación fallida: "Ha ocurrido un problema al tratar de guardar la venta. %{errores}"
- Actualización exitosa: "Se ha actualizado la venta exitosamente"
- Actualización fallida: "Ha ocurrido un problema al tratar de actualizar la venta. %{errores}"
- Eliminación exitosa: "Se ha eliminado la venta exitosamente"
- Eliminación fallida: "Ha ocurrido un problema al tratar de eliminar la venta. %{errores}"
