### ISSUE TITLE
Definir la documentación para el feature Movimientos de Cuenta Corriente

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#39]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by mlored** [comment]
### Movimientos de Cuenta Corriente

#### Descripción

Es el extracto de todos los movimientos de cada cuenta corriente. En la cuenta corriente se reflejará el saldo de todas las compras, ventas, cobros, pagos y devoluciones (para clientes y proveedores).
El actor sería el gerente.
La vista necesaria sería una única lista con los extractos de todos los movimientos de cada cliente o proveedor respectivamente, cuyo propósito sería reflejar los saldos de compras o ventas y devoluciones. Esta vista incluirá los filtros: entre dos fechas, por proveedor (o cliente si es la cuenta corriente de clientes) por tipo de movimiento (devoluciones, compras/ventas, pagos).

#### Flujo

No habrá formulario, debido a que se trata de un extracto (lista).

##### Flujo Normal
1. Se debe entrar en la opción de cuenta corriente y seleccionar el proveedor o el cliente.
2. Se muestran los primeros 25 movimientos de la cuenta corriente seleccionada (proveedores o clientes).
3. Además se muestra la opción para filtrar por fechas.
4. El gerente puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.
6. Se cuenta también con la opción de imprimir.

##### Flujo Alternativo

1.Desde el listado de compras y ventas se puede acceder al listado de cuenta corrientes, entrando en la opción de Movimientos que aparece junto a cada proveedor o cliente.
2. Se muestran los primeros 25 movimientos de la cuenta corriente seleccionada.
3. Además se muestra la opción para filtrar por fechas.
4. El gerente puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.
6. Se cuenta con la opción de imprimir.

#### Dependencias

Entre las dependencias tenemos:
1. ABM Proveedores
2. ABM Clientes
3. Movimientos Genéricos

#### Gemas necesarias

Se utilizarán las siguientes gemas:
1.  Ransack
Version: '~> 1.6.4'
Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
Version: '~> 1.16.3'
Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Enumerize
Version: '~> 0.11.0'
Utilización: para utilizar enums en los modelos.
4.  Simple_form
Version: '~> 3.2.0'
Utilización: para hacer los formularios mas simples.
5.  Paranoia
Version: '~> 2.1.0'
Utilización: para hacer borrado ocioso de registros automáticamente.
6.  Cocoon
Version: '~> 1.2.8'
Utilización: para formularios anidados dinámicos del lado del proveedor.

#### Prioridad

8

**Comment by bordonwork** [comment]
@mlored no me quedaron claras las vistas. Cuáles serían?

**Comment by mlored** [comment]
Fue un error mio pluralizar.
Es solo un listado de los movimientos de cuenta corriente

**Comment by mlored** [comment]
### Movimientos de Cuenta Corriente

#### Descripción

Es el extracto de todos los movimientos de cada cuenta corriente. En la cuenta corriente se reflejará el saldo de todas las compras, ventas y devoluciones (pueden ser de compra o de venta).
El actor sería el gerente.
El extracto seria el listado de todos los movimientos de cada cuenta corriente, cuyo propósito sería reflejar los saldos de compras, ventas y devoluciones.

Vistas
1. Listar

#### Flujo

No habrá formulario, debido a que se trata de un listado.

##### Listar
1. Se debe entrar en la opción de cuenta corriente y seleccionar el proveedor o el cliente.
2. Se muestran los ultimos 25 movimientos de la cuenta corriente seleccionada.
3. Además se muestra la opción para filtrar por fechas.
4. El gerente puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.
6. Se cuenta también con la opción de imprimir.

##### Flujo Alternativo

1.Desde el listado de compras y ventas se puede acceder al listado de cuenta corrientes, entrando en la opción de Movimientos que aparece junto a cada proveedor o cliente.
2. Se muestran los ultimos 25 movimientos de la cuenta corriente seleccionada.
3. Además se muestra la opción para filtrar por fechas.
4. El gerente puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.
6. Se cuenta con la opción de imprimir.

#### Dependencias

Entre las dependencias tenemos:
1. ABM Proveedores
2. ABM Clientes
3. Movimientos Genéricos

#### Gemas necesarias
1.  Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
4.  Paranoia
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.

**Observación:** nótese el operador pesimista(~>) para evitar que se incluyan cambios mayores de las gemas si en algún momento se hace un update. Estos son los que se usan ahora; puede cambiar en el futuro por diferentes razones(fixes,  mejoras, nuevos features, etc. en las gemas)

#### Prioridad

8
