### ISSUE TITLE
Implementar el formulario de login

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#4]
Depende de #2 
Implementar el formulario del login en base al diseño proveído:
![image](https://cloud.githubusercontent.com/assets/3639650/13547246/d7051522-e2a9-11e5-81d0-1d0fd8cdb4ff.png)

Se deberá validar los campos antes de enviar el formulario, tanto su longitud como su formato. Ver: Validatable en issue #2, [jquery-validation](https://github.com/jzaefferer/jquery-validation)

Esta vista debe realizarse en base al formulario generado por devise. Ver: `rails generate devise:install` [en la documentación](https://github.com/plataformatec/devise)

**Comment by carlosleite** [comment]
@mlored , para esta tarea hay que usar un layout diferente a application.html.slim. Aca indica como cambiar el layout para devise: [https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts#define-in-applicationcontroller](https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts#define-in-applicationcontroller)

Este layout debe estar basado en el [login de AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/pages/examples/login.html). El html de ejemplo esta en el repositorio en docs/AdminLTE-2.3.0/pages/examples/login.html

**Comment by louvelaz** [comment]
@mlored 
- Se debe poner un limite superior al campo Nombre de Usuario  
- En el mensaje de error "username o contraseña inválidos" username podría sustituirse por "Nombre de usuario" o algún otro nombre en español

**Comment by louvelaz** [comment]
@mlored  Todavía no tiene un limite superior el campo Nombre de Usuario
