### ISSUE TITLE
Definir la documentación para el feature Pagos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#40]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by LudisM** [comment]
### Descripcion

El feature de Pagos es utilizado para realizar los pagos correspondientes a compras pendientes de pagos, El pago se podra realizar solo en efectivo y en distintas monedas disponibles en el sistema, tambien esta asociado a créditos disponibles con el proveedor (que se generan con las devoluciones de mercaderías).

#### Actores

Usuario y Proveedor.

#### Vistas necesarias
- Crear
- Editar
- Listar

### Flujo

#### Vista Crear

##### Flujo
1. El usuario solicita al sistema comenzar el proceso de registro de pago de boletas de compras.
2. El usuario selecciona la/s boletas/s de compra a ser pagada/s.
3. El sistema muestra el monto a pagar.
4. El usuario ingresa los montos en las monedas disponibles en la que se paga la boleta de compra.
5. El usuario confirma el pago.
6. El sistema guarda los datos, actualiza los saldos correspondientes e informa al usuario que se registró el pago.

##### Flujo alternativo
1. El usuario solicita al sistema comenzar el proceso de registro de pago de boletas de compras.
2. El usuario selecciona la/s boletas/s de compra a ser pagada/s.
3. El sistema muestra el monto a pagar.
4. El usuario selecciona el credito generado por devoluciones.
5. El usuario confirma el pago.
6. El sistema guarda los datos, actualiza los saldos correspondientes e informa al usuario que se registró el pago.

###### Excepciones
1. el monto a pagar es mayor al credito disponible.

#### Vista Editar

##### Flujo
1. El usuario solicita editar un pago realizado.
2. El usuario modifica los campos que desea modificar.
3. El usuario confirma la edición.
4. El sistema guarda la edición, actualiza los saldos correspondientes e informa al usuario que se registró el pago editado.

##### Excepciones
1. el monto a pagar es mayor al credito disponible.

#### Vista Listar
1. Se debe entrar en la opción de Pagos
2. Se muestran las ultimos 25 pagos realizados.
3. Además se muestra la opción para filtrar por fechas, por número, por proveedor.
4. El usuario puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.
6. Se cuenta también con la opción de imprimir.

### Dependencias

Entre las dependencias tenemos:
1. ABM Mercaderias.
2. ABM Proveedores.
3. ABM Cuentas Corrientes

### Gemas Necesarias
1. Ransack.
   Version: '~> 1.6.4'
   Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari.
   Version: '~> 1.16.3'
   Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Enumerize.
   Version: '~> 0.11.0'
   Utilización: para utilizar enums en los modelos.
4. Simple_form.
   Version: '~> 3.2.0'
   Utilización: para hacer los formularios mas simples.
5. Paranoia.
   Version: '~> 2.1.0'
   Utilización: para hacer borrado ocioso de registros automáticamente.
6. Cocoon.
   Version: '~> 1.2.8'
   Utilización: para formularios anidados dinámicos del lado del cliente.

### Prioridad

10

### Mensajes
1. Creación exitosa: "Se ha guardado el pago exitosamente"
2. Creación fallida: "Ha ocurrido un problema al tratar de guardar el pago. %{errores}"
3. Actualización exitosa: "Se ha actualizado el pago exitosamente"
4. Actualización fallida: "Ha ocurrido un problema al tratar de actualizar el pago. %{errores}"
5. Eliminación exitosa: "Se ha eliminado el pago exitosamente"
6. Eliminación fallida: "Ha ocurrido un problema al tratar de eliminar el pago. %{errores}"
