### ISSUE TITLE
Definir la documentación para el feature Devolución de Mercadería Compra/Venta

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#43]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by afaraldo** [comment]
FEATURE DEVOLUCIÓN DE MERCADERÍA COMPRA/VENTA

DESCRIPCIÓN
El feature devolución de mercadería es utilizado para realizar la devolución parcial o total de mercaderías compradas o vendidas. Se generan automáticamente movimientos de mercaderías y cuentas corrientes.

ACTORES
Usuario (gerente)

VISTAS
1.  Listar (Devolución de Compras y Devolución de Ventas)
2.  Crear (Devolución de Compras y Devolución de Ventas)
3.  Editar (Devolución de Compras y Devolución de Ventas)

FLUJOS
El flujo para devolución de compras es el mismo que el flujo para devolución de ventas, la única diferencia esta en que una devolución de compra actualizara el stock (restando la cantidad devuelta de la cantidad de stock, se permitirá stock negativo con la confirmación del usuario) y el saldo del proveedor (restando el importe total de la devolución del saldo), mientras que la devolución de compra aumentará el stock (sumando la cantidad devuelta al stock) y disminuira el saldo con el cliente (restando el importe total de la devolución al saldo del cliente)

NUEVA DEVOLUCIÓN
1.  Se selecciona la opcion  Devoluciónes de compras
2.  Se rellena los campos de la cabecera (fecha, proveedor). La fecha de las devoluciones no podrá ser una fecha futura.
3.  Se selecciona una de las compras del proveedor espeficado anteriormente.
4.  Se cargan las mercaderias y sus cantidades correspondientes a la compra especificada anteriormente 
5.  Se rellena los campos correspondientes a cantidad de mercaderias devuelta para cada mercadería.
6.  El total de la devolución de compra es igual a la suma de los precios de las mercaderías por sus cantidad devueltas correspondiente.
7.  El total de los detalles de la devolución diferente a cero debe ser igual al total de la devolución de compra. Se guardarán solo los detalles que tengan cantidad devueltas diferentes de cero.
8.  El usuario confirma la devolución.
9.  El sistema guarda la devolución e informa al usuario que se registró la misma.
10. Luego de guardar la devolución las cantidades de los detalles se deben reflejar en los movimientos de mercaderías y actualizar el saldo del proveedor en cuenta corriente.

EXCEPCIONES
1.  Si la cantidad de mercaderias devueltas es mayor al total de mercaderías vendidas no se debe guardar la compra. 

EDITAR DEVOLUCIÓN COMPRA
1.  El usuario solicita editar una devolución realizada.
        Solo se podrá editar y eliminar la devolución si el crédito de la misma no ha sido utilizado.
2.  El sistema muestra en el formulario los datos de la devolución . La fecha de las devoluciones no podrá ser una fecha futura.
3.  El usuario modifica los campos que desea modificar, excepto los datos de las ventas y el proveedor.
4.  El usuario confirma la edición.
5.  Se debe verificar si las cantidades introducidas puede causar existencia negativa.
6.  Se deben hacer las actualizaciones de stock y cueta corriente necesarias en caso de que se haya modificado alguna de las cantidades.
7.  El sistema guarda la edición e informa al usuario que se registró la edición.

EXCEPCIONES
1.  Si las modificaciones de cantidades pueden causar stock negativo se debe advertir al usuario y dar la opción de continuar de todos modos o cancelar la modificacion de la devolución de compra.

LISTAR DEVOLUCIONES COMPRAS
1.  Se debe entrar en la opción de devolución de compra.
2.  Se muestran las ultimas 25 devoluciones de compras realizadas.
3.  Además se muestra la opción para filtrar por fecha y por proveedor o cliente.
4.  El usuario puede aplicar los filtros deseados.
5.  El sistema muestra el listado con los filtros aplicados.

DEPENDENCIAS
1.  ABM Mercaderias.
2.  ABM Proveedores.
3.  ABM Compras.
4.  Cuentas Corrientes.

GEMAS NECESARIAS
1.  Ransack 
o   Version: '~> 1.6.4'
o   Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari 
o   Version: '~> 1.16.3'
o   Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Enumerize 
o   Version: '~> 0.11.0'
o   Utilización: para utilizar enums en los modelos.
4.  Simple_form 
o   Version: '~> 3.2.0'
o   Utilización: para hacer los formularios mas simples.
5.  Paranoia 
o   Version: '~> 2.1.0'
o   Utilización: para hacer borrado ocioso de registros automáticamente.
6.  Cocoon 
o   Version: '~> 1.2.8'
o   Utilización: para formularios anidados dinámicos del lado del cliente.

Observación: notese el operador pesimista(~>) para evitar que se incluyan cambios mayores de las gemas si en algun momento se hace un update. Estos son los que se usan ahora; puede cambiar en el futuro por diferentes razones(fixes, mejoras, nuevos features, etc. en las gemas)

PRIORIDAD
5

MENSAJES
POSIBLE STOCK NEGATIVO: "La operación va a provocar existencia negativa en los siguientes productos: %{productos}. Esta seguro que quiere continuar? [Continuar] | [Cancelar]"
CREACIÓN EXITOSA: "Se ha guardado la devolución exitosamente"
CREACIÓN FALLIDA: "Ha ocurrido un problema al tratar de guardar la devolución. %{errores}"
ACTUALIZACIÓN EXITOSA: "Se ha actualizado la devolución exitosamente"
ACTUALIZACIÓN FALLIDA: "Ha ocurrido un problema al tratar de actualizar la devolución. %{errores}"
ELIMINACIÓN EXITOSA: "Se ha eliminado la devolución exitosamente"
        Solo se podrá editar y eliminar la devolución si el crédito de la misma no ha sido utilizado.
ELIMINACIÓN FALLIDA: "Ha ocurrido un problema al tratar de eliminar la devolución. %{errores}"
