### ISSUE TITLE
Definir la documentación para el feature Reportes de Compras

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#44]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by carlosleite** [comment]
### Descripcion

El feature de reporte de compras genera un reporte de todas las compras realizadas, estos reportes pueden ser filtrados por fechas y agrupar de acuerdo a lo que necesita el usuario, por defecto muestra la agrupacion por dia. Las agrupaciones pueden ser:
1. Periodo(dia, mes o año):
   1. Al seleccionar Periodo por defecto se muestra por dia:
      
      **01/03/2016**
      - Compra Nro 1
      - Compra Nro 2
      - Compra Nro 3
      - Compra Nro 4
      - Compra Nro 5
      
      **02/03/2016**
      - Compra Nro 1
      - Compra Nro 2
      - Compra Nro 3
      - Compra Nro 4
      - Compra Nro 5
        ...
      
      _Modo resumido:_
      **01/03/2016**  TOTAL_DEL_DIA
      **02/03/2016**  TOTAL_DEL_DIA
      **03/03/2016**  TOTAL_DEL_DIA
      ...
   2. Si selecciona por mes:
      
      **Enero**
      - Compra Nro 1
      - Compra Nro 2
      - Compra Nro 3
      
      **Febrero**
      - Compra Nro 4
      - Compra Nro 5
        ...
      
      _Modo resumido:_
      **Enero**   TOTAL_DEL_MES
      **Febrero** TOTAL_DEL_MES
      **Marzo**   TOTAL_DEL_MES
2. Proveedores: Funcionaría de la misma forma que por periodo.
3. Modo resumido: Son los resumenes por agrupacion como muestra los ejemplos en los puntos anteriores.

#### Actores

Usuario

#### Vistas relacionadas
1. Listar

### Flujo
1. El sistema por defecto muestra una lista de las últimas compras realizadas por defecto agrupado por dia. Además muestra opciones para filtrar y agrupar dicha lista.
2. El usuario puede aplicar los filtros y agrupaciones deseados.
3. El sistema muestra el reporte con los filtros y agrupaciones aplicados.
4. El reporte generado tendrá una opción para imprimir el reporte.

### Dependencias
1. ABM Proveedores
2. ABM Compras

### Gemas Necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.

### Prioridad

6

### Observaciones

En cuanto a las compras que haya tenido una devolucion en el reporte se refleja: 
    - El total de la compra menos el total devuelto.
    - Si la compra se anulo totalmente con la devolucion esa compra no se muestra en el reporte.

**Comment by carlosleite** [comment]
### Descripcion

El feature de reporte de compras genera un reporte de todas las compras realizadas, estos reportes pueden ser filtrados por fechas y agrupar de acuerdo a lo que necesita el usuario, por defecto muestra la agrupacion por dia. Las agrupaciones pueden ser:
1. Periodo(dia, mes o año):
   1. Al seleccionar Periodo por defecto se muestra por dia:
      
      **01/03/2016**
      - Compra Nro 1
      - Compra Nro 2
      - Compra Nro 3
      - Compra Nro 4
      - Compra Nro 5
      
      **02/03/2016**
      - Compra Nro 1
      - Compra Nro 2
      - Compra Nro 3
      - Compra Nro 4
      - Compra Nro 5
        ...
      
      _Modo resumido:_
      **01/03/2016**  TOTAL_DEL_DIA
      **02/03/2016**  TOTAL_DEL_DIA
      **03/03/2016**  TOTAL_DEL_DIA
      ...
   2. Si selecciona por mes:
      
      **Enero**
      - Compra Nro 1
      - Compra Nro 2
      - Compra Nro 3
      
      **Febrero**
      - Compra Nro 4
      - Compra Nro 5
        ...
      
      _Modo resumido:_
      **Enero**   TOTAL_DEL_MES
      **Febrero** TOTAL_DEL_MES
      **Marzo**   TOTAL_DEL_MES
2. Proveedores: Funcionaría de la misma forma que por periodo.
3. Modo resumido: Son los resumenes por agrupacion como muestra los ejemplos en los puntos anteriores.

Cuando el reporte es resumido se mostrará un grafico estadistico. Cuando la serie a agrupar es de tiempo como Día, mes y año el grafico será linear y para proveedor en barras.

#### Actores

Usuario

#### Vistas relacionadas
1. Listar

### Flujo
1. El sistema por defecto muestra una lista de las compras realizadas en el mes actual por defecto agrupado por dia. Además muestra opciones para filtrar y agrupar dicha lista.
2. El usuario puede aplicar los filtros y agrupaciones deseados.
3. El sistema muestra el reporte con los filtros y agrupaciones aplicados.
4. El reporte generado tendrá una opción para imprimir el reporte.

### Dependencias
1. ABM Proveedores
2. ABM Compras

### Gemas Necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.

### Libreria para los graficos

[Chart.js](https://github.com/nnnick/Chart.js/releases) Version 2+

### Prioridad

6

### Observaciones

En cuanto a las compras que haya tenido una devolucion en el reporte se refleja: 
    - El total de la compra menos el total devuelto.
    - Si la compra se anulo totalmente con la devolucion esa compra no se muestra en el reporte.
