### ISSUE TITLE
Definir la documentación para el feature Reportes de Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#45]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by LudisM** [comment]
### Descripcion

El feature de reporte de ventas genera un reporte de todas las ventas realizadas, estos reportes pueden ser filtrados por fechas y agrupar de acuerdo a lo que necesita el usuario. Las agrupaciones pueden ser:
1. Por dia: muestra el reporte de todas las ventas realizadas en ese dia.
2. Por cliente: muestra el reporte de todas las ventas de entre las fechas de todos los clientes. Al seleccionar esta agrupación se podrá filtrar por cliente y esto muestra el reporte de las ventas realizadas entre las fechas de ese cliente.
3. Modo resumido: muestra el reporte de todas las ventas resumidas por mes. 

#### Actores

Usuario

#### Vistas relacionadas
1. Listar

### Flujo
1. El sistema por defecto muestra una lista de las últimas ventas realizadas. Además muestra opciones para filtrar y agrupar dicha lista.
2. El usuario puede aplicar los filtros deseados.
3. El sistema muestra el reporte con los filtros aplicados.
4. El reporte generado tendrá una opción para imprimir el reporte.

### Dependencias
1. ABM Cliente
2. ABM Ventas

### Gemas Necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.

### Prioridad

6

**Comment by afaraldo** [comment]
@LudisM Yo opino que quedaría más claro el texto de la siguiente forma: El feature de reporte de ventas genera una lista de todas las ventas realizadas entre dos período de tiempos (los cuales podrán ser cambiados a través de un filtro, por defecto se tomará el primer y último día del corriente año), esta lista de ventas podrá ser agrupada de acuerdo a lo que necesita el usuario. Las agrupaciones pueden ser: (elegir una agrupación es obligatorio)
1. Por dia: muestra el reporte de todas las ventas realizadas en por dias. (por defecto)
2. Por mes:
3. Por año:
4. Por cliente: muestra el reporte de todas las ventas por clientes.
Además será opcional seleccionar un "Modo resumido:"  muestra el reporte de todas las ventas resumidas con sus totales.

**Comment by carlosleite** [comment]
@afaraldo , creo que el rango de fecha predeterminado debe ser el primer y último día del corriente mes. Una año pueden ser muchas ventas.

**Comment by LudisM** [comment]
@afaraldo Lo que sugieres es que tengamos 4 agrupaciones mas 1 opcional? hasta donde tengo entendido todas las agrupaciones serán opcionales que serian:
1. Por dia: que muestra las ventas realizadas entre las  fechas ( desde - hasta) que se pone en el filtro.
2. Por cliente: muestra las ventas realizadas del mismo entre las  fechas ( desde - hasta) que se pone en el filtro.
3. Modo resumido: Muestra las ventas totales resumidas por mes entre las  fechas ( desde - hasta) que se pone en el filtro.
Y si no se utiliza ningun filtro por defecto muestra las ventas realizadas desde el primer dia hasta el ultimo dia del mes actual,
no se si esta bien asi, si no es asi pueden corregirme @carlosleite @afaraldo 
Y si creen conveniente agregar una agrupacion mas que seria por año.

**Comment by carlosleite** [comment]
Asi lo veo yo:

Por defecto el reporte muestra el listado de las ventas del mes actual.

Tendrá filtros de rango de fechas, clientes, quizas condicion de pago y estado tambien. Esto funciona exactamente igual que el "Listar" de ventas.

Tendrá opciones de agrupar la lista de ventas. Se podrá resumir las agrupaciones con un checkbox o boton. Se podrá agrupar por: 
1. Periodo(dia, mes o año): 
   1. Al seleccionar Periodo por defecto se muestra por dia:
      **01/03/2016**
      - Venta Nro 1
      - Venta Nro 2
      - Venta Nro 3
      - Venta Nro 4
      - Venta Nro 5
      
      **02/03/2016**
      - Venta Nro 1
      - Venta Nro 2
      - Venta Nro 3
      - Venta Nro 4
      - Venta Nro 5
        ...
      
      _Modo resumido:_
      **01/03/2016**  TOTAL_DEL_DIA
      **02/03/2016**  TOTAL_DEL_DIA
      **03/03/2016**  TOTAL_DEL_DIA
      ...
   2. Si selecciona por mes:
      **Enero**
      - Venta Nro 1
      - Venta Nro 2
      - Venta Nro 3
      
      **Febrero**
      - Venta Nro 4
      - Venta Nro 5
        ...
      
      _Modo resumido:_
      **Enero**   TOTAL_DEL_MES
      **Febrero** TOTAL_DEL_MES
      **Marzo**   TOTAL_DEL_MES
2. Clientes, Condicion de pago, estado: Funcionaria de la misma forma que por periodo.

Parece algo complejo porque hay muchas opciones pero es muy útil. Cuando hagamos el UI probablemente quede mas claro y le mostramos al Cliente. Ella creo nos va a poder decir si es lo que espera o si necesita solo algunos reportes específicos.

**Comment by LudisM** [comment]
### Descripcion

El feature de reporte de ventas genera un reporte de todas las ventas realizadas, estos reportes pueden ser filtrados por fechas y agrupar de acuerdo a lo que necesita el usuario, por defecto muestra la agrupacion por dia.. Las agrupaciones pueden ser:
1. Periodo(dia, mes o año):
   1. Al seleccionar Periodo por defecto se muestra por dia:
      
      **01/03/2016**
      - Venta Nro 1
      - Venta Nro 2
      - Venta Nro 3
      - Venta Nro 4
      - Venta Nro 5
      
      **02/03/2016**
      - Venta Nro 1
      - Venta Nro 2
      - Venta Nro 3
      - Venta Nro 4
      - Venta Nro 5
        ...
      
      _Modo resumido:_
      **01/03/2016**  TOTAL_DEL_DIA
      **02/03/2016**  TOTAL_DEL_DIA
      **03/03/2016**  TOTAL_DEL_DIA
      ...
   2. Si selecciona por mes:
      
      **Enero**
      - Venta Nro 1
      - Venta Nro 2
      - Venta Nro 3
      
      **Febrero**
      - Venta Nro 4
      - Venta Nro 5
        ...
      
      _Modo resumido:_
      **Enero**   TOTAL_DEL_MES
      **Febrero** TOTAL_DEL_MES
      **Marzo**   TOTAL_DEL_MES
2. Clientes: Funcionaria de la misma forma que por periodo.
3. Modo resumido: Son los resumenes por agrupacion como muestra los ejemplos en los puntos anteriores.

#### Actores

Usuario

#### Vistas relacionadas
1. Listar

### Flujo
1. El sistema por defecto muestra una lista de las ventas realizadas en el mes actual por defecto agrupado por dia . Además muestra opciones para filtrar y agrupar dicha lista.
2. El usuario puede aplicar los filtros y agrupaciones deseados.
3. El sistema muestra el reporte con los filtros y agrupaciones aplicados.
4. El reporte generado tendrá una opción para imprimir el reporte.

### Dependencias
1. ABM Cliente
2. ABM Ventas

### Gemas Necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.

### Prioridad

6

### Observaciones

En cuanto a las ventas que haya tenido una devolucion en el reporte se refleja: 
    - El total de la venta menos el total devuelto.
    - Si la venta se anulo totalmente con la devolucion esa venta no se muestra en el reporte.
