### ISSUE TITLE
Definir la documentación para el feature Reportes de Movimientos de Caja

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#46]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by mlored** [comment]
### Reportes de Movimientos de Caja

#### Descripción

Este feature de Reportes de Movimientos de Caja genera un reporte de todos los movimientos de caja que se hayan realizado. Puede ser filtrado por tipo de movimiento, fecha y agrupar de acuerdo a lo que necesita el usuario, por defecto muestra la agrupación por día.
El actor sería el gerente y/o usuario
Vistas
1. Listar

#### Flujo
1. El sistema por defecto muestra una lista de las movimientos realizados en el mes actual y por defecto agrupados por día.
2. Además muestra opciones para filtrar y agrupar dicha lista.
3. El usuario puede aplicar los filtros y agrupaciones deseados.
4. El sistema muestra el reporte con los filtros y agrupaciones aplicadas.
5. El reporte generado tendrá una opción para imprimir el reporte.

#### Dependencias
1. ABM Compras
2. ABM Ventas
3. ABM Movimientos de Caja

#### Gemas Necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.

#### Prioridad

6
