### ISSUE TITLE
Definir la documentación para el feature Reportes de Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#47]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by afaraldo** [comment]
Conversando con los compañeros, decidimos que la división entre los reportes de gastos y movimientos de caja no es necesario, es decir, como un gasto es un movimiento de caja de tipo egreso con una categoria de gasto esta se podrá representar en el reporte de caja agregando un filtro que permita mostrar solamente los movimientos que representan gastos. Esto se tendrá que detallar en el ticket correspondiente a movimientos de caja #42

**Comment by afaraldo** [comment]
Con respecto al comentario anterior, me confundí y si son diferentes los reportes de movimientos de caja y reporte de gastos. Hablando con los compañeros me aclararon la diferencia y agrego la descripción del feature corregido a continuación:

El feature de reporte de Gastos genera un reporte de todas los gastos realizados, estos reportes pueden ser filtrados por fechas y agrupar de acuerdo a lo que necesita el usuario, por defecto muestra la agrupacion por dia. Las agrupaciones pueden ser:
1. Periodo(dia, mes o año):
       Al seleccionar Periodo por defecto se muestra por dia:
       01/03/2016
             - Gasto Nro 1
             - Gasto Nro 2
             - Gasto Nro 3
             - Gasto Nro 4
             - Gasto Nro 5
       02/03/2016
             - Gasto Nro 1
             - Gasto Nro 2
             - Gasto Nro 3
             - Gasto Nro 4
             - Gasto Nro 5 ...
   
   ```
   Modo resumido:
         - 01/03/2016 TOTAL_DEL_DIA
         - 02/03/2016 TOTAL_DEL_DIA
         - 03/03/2016 TOTAL_DEL_DIA
         - ...
   
   Si selecciona por mes:
   Enero
       - Gasto Nro 1
       - Gasto Nro 2
       - Gasto Nro 3
   
   Febrero
       - Gasto Nro 4
       - Gasto Nro 5 ...
   
   Modo resumido:
       - Enero TOTAL_DEL_MES
       - Febrero TOTAL_DEL_MES
       - Marzo TOTAL_DEL_MES
   ```
   
   Categoría de Gasto: Funcionaría de la misma forma que por periodo.
   Modo resumido: Son los resumenes por agrupacion como muestra los ejemplos en los puntos anteriores.

**Actores**
Usuario

**Vistas relacionadas**
    - Listar

**Flujo**
    - El sistema por defecto muestra una lista de los gastos realizadas en el mes actual por defecto agrupado por dia. Además muestra opciones para filtrar y agrupar dicha lista.
    - El usuario puede aplicar los filtros y agrupaciones deseados.
    - El sistema muestra el reporte con los filtros y agrupaciones aplicados.
    - El reporte generado tendrá una opción para imprimir el reporte.

**Dependencias**
    ABM Movimientos de Caja
    ABM Categoria de Gastos

**Gemas Necesarias**
    Ransack
        Version: '~> 1.6.4'
        Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
    Kaminari
        Version: '~> 1.16.3'
        Utilización: para hacer las paginaciones de las colecciones mas simples.
    Simple_form
        Version: '~> 3.2.0'
        Utilización: para hacer los formularios mas simples.

**Prioridad**
6
