### ISSUE TITLE
Definir la documentación para el feature Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#48]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by afaraldo** [comment]
Como se menciono en el ticket #47, como un "gasto" es un "movimiento de egreso de caja" el mismo se creará como tal. Crear un gasto equivale entonces a crear un movimiento de caja, de tipo egreso y agregando una categorias de gastos. Esto deberá detallarse en el feature de movimientos de caja #42.

**Comment by bordonwork** [comment]
@afaraldo no tendrá ninguna vista?

**Comment by afaraldo** [comment]
@bordonwork. No, no tendrá ninguna vista. El feature en sí se elimina, porque su funcionalidad estará dentro de lo que es un movimiento de caja.
