### ISSUE TITLE
Definir la documentación para el feature Listar Movimientos por Mercaderias

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#49]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by carlosleite** [comment]
### Descripción

Es un listado donde se podrá ver cuando y como ingresó o salió determinada mercadería. Lista todos los movimientos de una mercadería en un rango de fecha con un balance.

#### Actores
- Usuario

#### Vistas
1. Listar

### Flujos

#### Listar
1. En el listado de Inventario debe haber un boton de "Movimientos" desde donde se podrá acceder a los mismos
2. En la vista de listar se debe tener una opción para cambiar de mercadería.
3. Se muestran los primeros 25 movimientos de la mercadería seleccionada.
4. Además se muestra la opción para filtrar por fechas.
5. El usuario puede aplicar los filtros deseados.
6. El sistema muestra el listado con los filtros aplicados.
7. Se cuenta también con la opción de imprimir.
   1. Se usa la opcion de imprimir del navegador para esta acción.

### Dependencias
1. ABM Mercaderias
2. Movimientos Genéricos

### Gemas necesarias
1.  Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.

**Observación:** notese el operador pesimista(~>) para evitar que se incluyan cambios mayores de las gemas si en algun momento se hace un update. Estos son los que se usan ahora; puede cambiar en el futuro por diferentes razones(fixes,  mejoras, nuevos features, etc. en las gemas)

### Prioridad:

6
