### ISSUE TITLE
Definir la documentación para el feature Mercaderías

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#50]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by LudisM** [comment]
### Descripcion

El feature de mercaderia se encarga del registro de nuevas mercaderias, la edicion de mercaderias y el listado de las mismas.

#### Actores

Usuario

#### Vistas relacionadas
1. Crear
2. Editar
3. Listar

### Flujo

#### Vista crear

##### Flujo
1. El usuario selecciona la opción de crear mercadería.
2. El sistema solicita los datos de la nueva mercadería.
3. El usuario rellena el formulario con los datos de la nueva mercadería.
4. El sistema verifica si ya hay alguna mercadería con el mismo código.
5. El usuario ingresa los precios de venta al contado y crédito dela mercadería.
6. El usuario confirma los datos a guardar.
7. El sistema guarda los datos y actualiza el inventario.

##### Excepciones
1. Si la mercadería ya existe, el sistema advierte al usuario.

#### Vista editar

##### Flujo
1. El usuario selecciona la mercaderia que desea editar.
2. El sistema muestra el formulario con los datos de la mercaderia seleccionada.
3. El usuario edita los campos que desea editar.
4. El usuario confirma la edicion.
5. El sistema guarda los cambios y actualiza el inventario.

#### Vista listar

##### Flujo
1. Se debe entrar en la opción de mercaderias.
2. Se muestran las ultimas 25 mercaderias.
3. Además se muestra la opción para filtrar por nombre, por codigo y por categoria.
4. El sistema muestra el listado con los filtros aplicados.

#### Eliminar mercaderia
1. Desde el listado de mercaderias el usuario debe seleccionar la opción de eliminar.
2. El usuario debe confirmar el borrado.
3. El borrado será ocioso

### Dependencias
1. ABM Categoria.

### Gemas Necesarias
1. Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3. Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
4. Paranoia
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.

### Prioridad

10

### Mensajes
1. Creación exitosa: "Se ha guardado la mercaderia exitosamente"
2. Creación fallida: "Ha ocurrido un problema al tratar de guardar la mercaderia. %{errores}"
3. Actualización exitosa: "Se ha actualizado la mercaderia exitosamente"
4. Actualización fallida: "Ha ocurrido un problema al tratar de actualizar la mercaderia. %{errores}"
5. Eliminación exitosa: "Se ha eliminado la mercaderia exitosamente"
   6.Eliminación fallida: "Ha ocurrido un problema al tratar de eliminar la mercaderia. %{errores}"
