### ISSUE TITLE
Definir la documentación para el feature Proveedores

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#51]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by afaraldo** [comment]
PROVEEDORES

DESCRIPCIÓN
Este feature será utilizado para tener el registro de todos los proveedores. Es de utilidad para el negocio debido a que el usuario puede tener registrado a todos sus proveedores e incluir a los nuevos.

ACTOR
El actor sería el gerente y/o usuario.

VISTAS
Las vistas necesarias serían:
1. Crear
2. Editar
3. Listar

FLUJO
CREAR PROVEEDOR
1. Se entra en la opción Nuevo proveedor.
2. Se completa el formulario con todos los campos requeridos y no requeridos si se desea.
3. El usuario selecciona la opción guardar.
4. El sistema guarda el nuevo proveedor e informa al usuario que se registró el proveedor.
5. Se incluye al listado de los proveedores el nuevo registro.

Editar Proveedor
1. Se pueden modificar los datos del formulario de un proveedor entrando en la opción editar que aparece al lado del proveedor dentro del listado de todos los proveedores.
2. El sistema muestra el formulario con los datos del proveedor.
3. El usuario modifica todos los datos que desea editar del proveedor dentro del formulario. 
4. El usuario confirma la edición en la opción guardar.
5. El sistema guarda los cambios e informa al usuario que se guardaron los cambios.
6. Se actualizan los cambios realizados dentro del listado de proveedores.

Eliminar proveedor
1. Se puede eliminar un proveedor seleccionando la opción eliminar que aparece al lado del proveedor dentro del listado de todos los proveedores.
2. El usuario confirma la eliminación.
3. El sistema borra el registro del listado de proveedores e informa que se eliminó el proveedor.
4. Se actualiza el listado de proveedores.

Listar Proveedores
1. Se entra en la opción proveedores dentro de la opción compras de la barra de menú.
2. Se muestra el listado de todos los proveedores registrados.
3. Además se muestra la opción para filtrar por nombre, por RUC/CI
4. El usuario puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.

Mensajes
Creación exitosa:_ "Se ha guardado el proveedor exitosamente"
Creación fallida: "Ha ocurrido un problema al tratar de guardar el proveedor. %{errores}"
Actualización exitosa: "Se ha actualizado el proveedor exitosamente"
Actualización fallida: "Ha ocurrido un problema al tratar de actualizar el proveedor. %{errores}"
Eliminación exitosa: "Se ha eliminado el proveedor exitosamente"
Eliminación fallida: "Ha ocurrido un problema al tratar de eliminar el proveedor. %{errores}"

Gemas Necesarias 
1. Ransack
Version: '~> 1.6.4'
Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2. Kaminari
Version: '~> 1.16.3'
Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Enumerize
Version: '~> 0.11.0'
Utilización: para utilizar enums en los modelos.
4.  Simple_form
Version: '~> 3.2.0'
Utilización: para hacer los formularios mas simples.
5.  Paranoia
Version: '~> 2.1.0'
Utilización: para hacer borrado ocioso de registros automáticamente.
6.  Cocoon
Version: '~> 1.2.8'
Utilización: para formularios anidados dinámicos del lado del proveedor.

Prioridad
10
