### ISSUE TITLE
Definir la documentación para el feature Clientes

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#52]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by mlored** [comment]
## Clientes

### Descripción

Este feature será utilizado para tener el registro de todos los clientes. Es de utilidad para el negocio debido a que el usuario puede tener registrado a todos sus clientes e incluir a los nuevos.
El actor sería el gerente y/o usuario.
Las vistas necesarias serían:
1. Listar
2. Editar
3. Crear
4. Eliminar

### Flujo

#### Flujo del Formulario

##### Listar Clientes
1. Se entra en la opción clientes dentro de la opción ventas de la barra de menú.
2. Se muestra el listado de todos los clientes registrados.
3. Además se muestra la opción para filtrar por nombre, por RUC/CI
4. El usuario puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.

##### Editar Cliente
1. Se pueden modificar los datos del formulario de un cliente entrando en la opción editar que aparece al lado del cliente dentro del listado de todos los clientes.
2. El sistema muestra el formulario con los datos del cliente.
3. El usuario modifica todos los datos que desea editar del cliente dentro del formulario. 
4. El usuario confirma la edición en la opción guardar.
5. El sistema guarda los cambios e informa al usuario que se guardaron los cambios.
6. Se actualizan los cambios realizados dentro del listado de clientes.

##### Crear Cliente
1. Se entra en la opción Nuevo Cliente.
2. Se completa el formulario con todos los campos requeridos y no requeridos si se desee.
3. El usuario selecciona la opción guardar.
4. El sistema guarda el nuevo cliente e informa al usuario que se registró el cliente.
5. Se incluye al listado de los clientes el nuevo registro.

##### Eliminar Cliente
1. Se puede eliminar un cliente seleccionando la opción eliminar que aparece al lado del cliente dentro del listado de todos los clientes.
2. El usuario confirma la eliminación.
3. El sistema borra el registro del listado de clientes e informa que se eliminó el cliente.
4. Se actualiza el listado de clientes.

##### Mensajes

_Creación exitosa:_ "Se ha guardado el cliente exitosamente"
_Creación fallida:_ "Ha ocurrido un problema al tratar de guardar el cliente. %{errores}"
_Actualización exitosa:_ "Se ha actualizado el cliente exitosamente"
_Actualización fallida:_ "Ha ocurrido un problema al tratar de actualizar el cliente. %{errores}"
_Eliminación exitosa:_ "Se ha eliminado el cliente exitosamente"
_Eliminación fallida:_ "Ha ocurrido un problema al tratar de eliminar el cliente. %{errores}"

### Gemas Necesarias
1.  Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Enumerize
   - Version: '~> 0.11.0'
   - Utilización: para utilizar enums en los modelos.
4.  Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
5.  Paranoia
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.
6.  Cocoon
   - Version: '~> 1.2.8'
   - Utilización: para formularios anidados dinámicos del lado del cliente.

### Prioridad

10

**Comment by LudisM** [comment]
@mlored Falta agregar los mensajes

**Comment by mlored** [comment]
mensajes y gemas agregados

**Comment by mlored** [comment]
## Clientes

### Descripción

Este feature será utilizado para tener el registro de todos los clientes. Es de utilidad para el negocio debido a que el usuario puede tener registrado a todos sus clientes e incluir a los nuevos.
El actor sería el gerente y/o usuario.
Las vistas necesarias serían:
1. Listar
2. Editar
3. Crear
4. Eliminar

### Flujo

#### Flujo del Formulario

##### Listar Clientes
1. Se entra en la opción clientes dentro de la opción ventas de la barra de menú.
2. Se muestra el listado de todos los clientes registrados.
3. Además se muestra la opción para filtrar por nombre, por RUC/CI
4. El usuario puede aplicar los filtros deseados.
5. El sistema muestra el listado con los filtros aplicados.

##### Editar Cliente
1. Se pueden modificar los datos del formulario de un cliente entrando en la opción editar que aparece al lado del cliente dentro del listado de todos los clientes.
2. El sistema muestra el formulario con los datos del cliente.
3. El usuario modifica todos los datos que desea editar del cliente dentro del formulario. 
4. El usuario confirma la edición en la opción guardar.
5. El sistema guarda los cambios e informa al usuario que se guardaron los cambios.
6. Se actualizan los cambios realizados dentro del listado de clientes.

##### Crear Cliente
1. Se entra en la opción Nuevo Cliente.
2. Se completa el formulario con todos los campos requeridos y no requeridos si se desee.
3. El usuario selecciona la opción guardar.
4. El sistema guarda el nuevo cliente e informa al usuario que se registró el cliente.
5. Se incluye al listado de los clientes el nuevo registro.

##### Eliminar Cliente
1. Se puede eliminar un cliente seleccionando la opción eliminar que aparece al lado del cliente dentro del listado de todos los clientes.
2. El usuario confirma la eliminación.
3. El sistema borra el registro del listado de clientes e informa que se eliminó el cliente.
4. Se actualiza el listado de clientes.

##### Mensajes

_Creación exitosa:_ "Se ha guardado el cliente exitosamente"
_Creación fallida:_ "Ha ocurrido un problema al tratar de guardar el cliente. %{errores}"
_Actualización exitosa:_ "Se ha actualizado el cliente exitosamente"
_Actualización fallida:_ "Ha ocurrido un problema al tratar de actualizar el cliente. %{errores}"
_Eliminación exitosa:_ "Se ha eliminado el cliente exitosamente"
_Eliminación fallida:_ "Ha ocurrido un problema al tratar de eliminar el cliente. %{errores}"

### Gemas Necesarias
1.  Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Enumerize
   - Version: '~> 0.11.0'
   - Utilización: para utilizar enums en los modelos.
4.  Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
5.  Paranoia
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.
6.  Cocoon
   - Version: '~> 1.2.8'
   - Utilización: para formularios anidados dinámicos del lado del cliente.

**Observación:** nótese el operador pesimista(~>) para evitar que se incluyan cambios mayores de las gemas si en algún momento se hace un update. Estos son los que se usan ahora; puede cambiar en el futuro por diferentes razones(fixes,  mejoras, nuevos features, etc. en las gemas)

### Prioridad

10
