### ISSUE TITLE
Definir la documentación para el feature Cotizaciones

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#53]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el cliente llega y pide un producto).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).
.

**Comment by carlosleite** [comment]
### Descripción

El sistema tendrá la posibilidad de hacer cobros y pagos en efectivo en diferentes monedas. Estas monedas serán definidas en el ABM de cotizaciónes. Tendrá una moneda base que es el Guaraní cuya cotización(1) no podrá ser modificada.

#### Actores

usuario.

#### Vistas
1. Listar
2. Crear
3. Editar

### Flujos

#### Nueva Moneda
1. Se selecciona la opcion de Nueva moneda
2. Se rellena los campos
3. El usuario confirma la moneda.
4. El sistema guarda la moneda e informa al usuario que se registró la moneda.

##### Excepciones
1. El sistema no debe dejar guardar si el nombre o la abreviatura de la moneda ya existe en la base de datos.

#### Editar Moneda
1. El usuario solicita editar una moneda.
2. El sistema muestra el formulario con los datos.
3. El usuario modifica los campos que desea modificar.
4. El usuario confirma la edición.

##### Excepciones
1. El sistema no debe dejar guardar si el nombre o la abreviatura de la moneda ya existe en la base de datos.

#### Listar Moneda
1.  Se debe entrar en la opción de monedas.
2.  Se muestran las ultimas 25 monedas.
3.  Además se muestra la opción para filtrar por nombre.
4.  El sistema muestra el listado con los filtros aplicados.

#### Eliminar Moneda
1. Desde el listado de monedas el usuario debe seleccionar la opción de eliminar.
2. El usuario debe confirmar el borrado.
3. El borrado será ocioso.

##### Excepciones
1. La moneda base(Guaraní) no se podrá eliminar.

### Dependencias
1.  Ninguna

### Gemas necesarias
1.  Ransack
   - Version: '~> 1.6.4'
   - Utilización: para hacer las búsquedas avanzadas (filtros) mas simples.
2.  Kaminari
   - Version: '~> 1.16.3'
   - Utilización: para hacer las paginaciones de las colecciones mas simples.
3.  Simple_form
   - Version: '~> 3.2.0'
   - Utilización: para hacer los formularios mas simples.
4.  Paranoia
   - Version: '~> 2.1.0'
   - Utilización: para hacer borrado ocioso de registros automáticamente.

**Observación:** notese el operador pesimista(~>) para evitar que se incluyan cambios mayores de las gemas si en algun momento se hace un update. Estos son los que se usan ahora; puede cambiar en el futuro por diferentes razones(fixes,  mejoras, nuevos features, etc. en las gemas)

### Prioridad

8

### Mensajes

_Creación exitosa:_ "Se ha guardado la moneda exitosamente"
_Creación fallida:_ "Ha ocurrido un problema al tratar de guardar la moneda. %{errores}"
_Actualización exitosa:_ "Se ha actualizado la moneda exitosamente"
_Actualización fallida:_ "Ha ocurrido un problema al tratar de actualizar la moneda. %{errores}"
_Eliminación exitosa:_ "Se ha eliminado la moneda exitosamente"
_Eliminación fallida:_ "Ha ocurrido un problema al tratar de eliminar la moneda. %{errores}"
