### ISSUE TITLE
Diseñar la vista para el ABM Clientes

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#54]
En base a la descripción del issue #28 diseñar las vistas:
- Listar
- Nuevo/Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by LudisM** [comment]
### Nuevo cliente

![nuevo-cliente](https://cloud.githubusercontent.com/assets/3651168/14158845/834ddbf2-f6a0-11e5-93fa-12a3033d6cd5.png)

### Editar cliente

![editar-cliente](https://cloud.githubusercontent.com/assets/3651168/14158863/95131d70-f6a0-11e5-892f-0b349494d450.png)

### Listar cliente

![listar-cliente](https://cloud.githubusercontent.com/assets/3651168/14158873/a0d644b6-f6a0-11e5-9de4-314859828b2e.png)

**Comment by bordonwork** [comment]
No sería un desperdicio de espacio los campos innecesariamente grandes?

**Comment by afaraldo** [comment]
Es cierto que puede parecer un campo innecesariamente grande, pero no hay desperdicio porque no hay más campos o lugares de la pantalla que utilizar mientras se trabaja con el formulario.

Hacerlo más pequeño reduciría podría reducir el tamaño del modal, lo cual podría dificultar su utilización y estetica.

**Comment by mlored** [comment]
concuerdo con @afaraldo, inclusive antes teniamos la opción para expandir más, pero la quitamos para mejorarla
