### ISSUE TITLE
Diseñar la vista para el ABM Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#55]
En base a la descripción del issue #37  diseñar las vistas:
- Listar
- Nuevo/Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by afaraldo** [comment]
**Listado Ventas**
![captura de pantalla de 2016-04-02 18 53 14](https://cloud.githubusercontent.com/assets/3640962/14230058/3755e9ee-f95a-11e5-96c4-6b946ce374c3.png)

Nueva Venta / Editar venta al contado
![captura de pantalla de 2016-04-02 19 27 19](https://cloud.githubusercontent.com/assets/3640962/14230077/ba4e1d44-f95a-11e5-8a20-58a8742b7cd6.png)

Nueva Venta / Editar venta - Agregar Devolucion
![captura de pantalla de 2016-04-02 19 24 00](https://cloud.githubusercontent.com/assets/3640962/14230068/832fe8d8-f95a-11e5-9ecc-c3f96f562377.png)

Nueva Venta / Editar venta - Con credito de Devoluciones
![captura de pantalla de 2016-04-02 20 19 43](https://cloud.githubusercontent.com/assets/3640962/14230073/a17130b8-f95a-11e5-88a0-93a073fb7696.png)

Nueva Venta / Editar venta - Mensaje de stock negativo
![captura de pantalla de 2016-04-02 20 35 25](https://cloud.githubusercontent.com/assets/3640962/14230083/e57fc9ae-f95a-11e5-8633-2ae9df0f385d.png)

Nueva venta / Editar venta a credito
![captura de pantalla de 2016-04-02 20 58 09](https://cloud.githubusercontent.com/assets/3640962/14230088/062843c0-f95b-11e5-9f2b-904b1d879fac.png)

**Show de Venta**
![8b8195a4-fab3-11e5-816c-74e82d01aab4](https://cloud.githubusercontent.com/assets/3640962/14282584/1eba04c2-fb50-11e5-8fc4-1e4b28dc81b4.png)
(Obs.: Identico a la interfaz del show de compras, solo se modifica las palabras proveedor por cliente, pagar por cobrar, compra por venta)
