### ISSUE TITLE
Diseñar las vistas para el ABM Compras

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#56]
En base a la descripción del issue #35 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by carlosleite** [comment]
### Listar Compras

![screenshot 2016-04-01 00 28 58](https://cloud.githubusercontent.com/assets/1580982/14197808/ce891ea0-f7a0-11e5-8b66-bf1425126c87.png)

### Nueva compra a crédito

![screenshot 2016-04-01 00 26 42](https://cloud.githubusercontent.com/assets/1580982/14197817/e0ad1780-f7a0-11e5-903a-3c438a987aed.png)

**Comment by carlosleite** [comment]
### Listado de Compras

![screenshot 2016-04-01 23 15 29](https://cloud.githubusercontent.com/assets/1580982/14224133/c5a84ed6-f85f-11e5-98cf-2aaa8e47b05e.png)

### Nueva Compra / Editar compra al contado

![screenshot 2016-04-01 22 22 41](https://cloud.githubusercontent.com/assets/1580982/14224140/e5806284-f85f-11e5-811d-fc7b0b40c542.png)

### Nueva Compra / Editar compra - Agregar Devolucion

![screenshot 2016-04-01 22 38 24](https://cloud.githubusercontent.com/assets/1580982/14224146/42d1ebf6-f860-11e5-8419-1c355a14895c.png)

### Nueva Compra / Editar compra - Con credito de Devoluciones

![condev](https://cloud.githubusercontent.com/assets/1580982/14224147/5b29e79e-f860-11e5-9672-26caf676572b.jpg)

### Nueva Compra / Editar compra - Mensaje de stock negativo

![screenshot 2016-04-01 23 06 15](https://cloud.githubusercontent.com/assets/1580982/14224155/6d7cd2da-f860-11e5-89d2-e1312e9c0c98.png)

### Nueva Compra / Editar compra a credito

![screenshot 2016-04-01 21 45 38](https://cloud.githubusercontent.com/assets/1580982/14224162/8ff9bdbe-f860-11e5-9953-963bd25d53de.png)

**Comment by carlosleite** [comment]
#### Vista de compra al contado

![screenshot 2016-04-04 22 19 36](https://cloud.githubusercontent.com/assets/1580982/14269526/850f9950-fab3-11e5-9c7c-a1c02291aa6d.png)

#### Vista de compra a crédito

![screenshot 2016-04-04 22 20 33](https://cloud.githubusercontent.com/assets/1580982/14269529/8b8195a4-fab3-11e5-816c-74e82d01aab4.png)
