### ISSUE TITLE
Diseñar el ABM de Pagos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#57]
En base a la descripción del issue #40 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by afaraldo** [comment]
**Listado de Cobros**
![captura de pantalla de 2016-04-04 13 32 53](https://cloud.githubusercontent.com/assets/3640962/14264451/e23b0f84-fad0-11e5-8cad-25d52c9c15d1.png)

**Listado de Pagos**
![captura de pantalla de 2016-04-04 13 33 26](https://cloud.githubusercontent.com/assets/3640962/14264600/180f42ce-fad1-11e5-9189-15beaf20d3e3.png)

**Nuevo pago / editar pago**
![captura de pantalla de 2016-04-05 06 53 43](https://cloud.githubusercontent.com/assets/3640962/14280536/54a60d3a-fb44-11e5-9230-6d8973a0b856.png)

**Nuevo pago / editar pago - agregar  devolución**
![captura de pantalla de 2016-04-05 06 54 04](https://cloud.githubusercontent.com/assets/3640962/14280563/89c870c0-fb44-11e5-9e46-2dcfee01d21d.png)

**Nuevo pago / editar pago - con credito devolucion**
![captura de pantalla de 2016-04-05 06 58 24](https://cloud.githubusercontent.com/assets/3640962/14280573/9d8530a8-fb44-11e5-9c9c-7c5f8757168f.png)

Nuevo cobro / editar cobro
![captura de pantalla de 2016-04-05 07 07 55](https://cloud.githubusercontent.com/assets/3640962/14280582/b12f23b6-fb44-11e5-81da-0d72d627cf7f.png)
