### ISSUE TITLE
Diseñar el ABM de Cotizaciones

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#58]
En base a la descripción del issue #53 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by LudisM** [comment]
### Listar

![listar-cotizacion](https://cloud.githubusercontent.com/assets/3651168/14206864/1fbda852-f7e4-11e5-8625-78d279516683.png)

### Nuevo

![nueva-cotizacion](https://cloud.githubusercontent.com/assets/3651168/14206868/338ee1e8-f7e4-11e5-808b-fc8f5cd5bbcf.png)

### Editar

![editar-cotizacion](https://cloud.githubusercontent.com/assets/3651168/14206877/44eeebea-f7e4-11e5-9426-dc6e98e08f81.png)

**Comment by carlosleite** [comment]
@LudisM en este caso se puede usar el modal #main-modal-sm para el formulario. Son pocos campos y nunca van a ser largos los contenidos.

**Comment by LudisM** [comment]
### Listar

![listar-cotizacion](https://cloud.githubusercontent.com/assets/3651168/14222982/639b3078-f846-11e5-83ec-1bc9d506798b.png)

### Nuevo

![nueva-cotizacion](https://cloud.githubusercontent.com/assets/3651168/14222984/661d2982-f846-11e5-8e9f-d38b413cc3bf.png)

### Editar

![editar-cotizacion](https://cloud.githubusercontent.com/assets/3651168/14222989/7b1a5ed6-f846-11e5-9fa5-855ab9d0fec5.png)
