### ISSUE TITLE
Diseñar el ABM de Categorías de Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#59]
En base a la descripción del issue #41 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by carlosleite** [comment]
### Listar categorias de gastos

![screenshot 2016-04-01 23 12 00](https://cloud.githubusercontent.com/assets/1580982/14224169/de482bb8-f860-11e5-87ce-815a4dad3196.png)

### Nueva categoria de gastos

![screenshot 2016-04-01 23 12 43](https://cloud.githubusercontent.com/assets/1580982/14224172/eabfff74-f860-11e5-93bc-5a7c8a0868f4.png)

### Editar categoria de gastos

![screenshot 2016-04-01 23 13 10](https://cloud.githubusercontent.com/assets/1580982/14224173/f3f78152-f860-11e5-93d2-ba8baf687bd2.png)
