### ISSUE TITLE
Realizar ABM de Usuarios

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#6]
Depende del issue #2 y #7
Se requiere generar el ABM para el modelo Usuarios. Esto incluye:
- Agregar un usuario.
- Editar un usuario.
- Eliminar un usuario(borrado ocioso).
- Listar usuarios.

Los formularios deben estar validados. Ver [jquery-validation](https://github.com/jzaefferer/jquery-validation)

**Comment by afaraldo** [comment]
El anterior movimiento de In Pogress a To Review fue un accidente.
Tiempo empleado en la tarea 10hs.

**Comment by carlosleite** [comment]
url para testear: https://casa-de-las-pinturas-test.herokuapp.com/empleados

**Comment by louvelaz** [comment]
@afaraldo 
- En el mensaje de error se debe especificar el formato correcto para Nombre de usuario, no solo decir que es inválido.
- La contraseña debe contener una combinación de números, letras (minúsculas y mayúsculas) y símbolos, esto ya lo había puesto en la tarea de @mlored, nose si lo van a configurar en el device o aca
- El campo Nro. de documento debería aceptar solo números
- El buscador no busca por CI, solo por Nombre
- En esta situación no se guarda en la base de datos, pero no muestra el mensaje de error, creo que se debe porque en la base de datos figura max 30 para Nro. de documento, pero en el ABM permite hasta 50

![usuario test mozilla 13_2](https://cloud.githubusercontent.com/assets/6853236/13940621/fa9c10d2-efbd-11e5-9318-4f778063079b.jpg)

**Comment by louvelaz** [comment]
@afaraldo 
- En este mensaje de error se repite 2 veces Contraseña

![error 3](https://cloud.githubusercontent.com/assets/6853236/13975070/69dc179e-f090-11e5-93b2-edee5acdc1db.jpg)
- Cada vez que se edita un usuario se tiene que volver a escribir la contraseña previamente guardada
- Hay inconsistencia de validaciones para un mismo campo 

![error 2](https://cloud.githubusercontent.com/assets/6853236/13975076/829024c4-f090-11e5-8127-0aa50346828e.jpg)

![error](https://cloud.githubusercontent.com/assets/6853236/13975080/8d1b0d46-f090-11e5-862b-ff44d477e0f1.jpg)
- Cuando en varios usuarios se utiliza el limite superior de longitud de varios campos, la grilla se desarregla y desaparecen los botones borrar y editar

![desaparecen con campos largos](https://cloud.githubusercontent.com/assets/6853236/13975092/a668eac0-f090-11e5-8a3c-6503720e47a8.jpg)
