### ISSUE TITLE
Diseñar la vista Listar Movimientos de Mercaderías

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#60]
En base a la descripción del issue #49 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by LudisM** [comment]
### Listar

![screenshot 2016-04-12 01 54 33](https://cloud.githubusercontent.com/assets/1580982/14451043/a27c7d02-0051-11e6-9ecb-50737ea4993a.png)

### Nuevo

![nuevo-mov-merc](https://cloud.githubusercontent.com/assets/3651168/14223547/415a327c-f84e-11e5-8cb1-1fdddb0073b3.png)

### Mensaje de alerta por posible stock negativo

![screenshot 2016-04-12 01 55 07](https://cloud.githubusercontent.com/assets/1580982/14451048/b6dcd616-0051-11e6-9891-912faf12a877.png)

### Editar

![editar-mov-mec](https://cloud.githubusercontent.com/assets/3651168/14223554/58ab4416-f84e-11e5-96fa-6f4b2064e09a.png)

### Mostrar

![mostrar-mov-merc](https://cloud.githubusercontent.com/assets/3651168/14223557/6a8ada5c-f84e-11e5-8b24-0559b76ddfb8.png)
