### ISSUE TITLE
Diseñar el ABM de Mercaderías

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#61]
En base a la descripción del issue #50 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by mlored** [comment]
## ABM de Mercaderías

### Vistas

#### Listar Mercaderías

![captura de pantalla 2016-04-01 02 04 02](https://cloud.githubusercontent.com/assets/6784862/14198519/08d68388-f7a9-11e5-9343-fd3dc656d9fa.png)

#### Nueva Mercadería

![captura de pantalla 2016-04-01 02 05 19](https://cloud.githubusercontent.com/assets/6784862/14198538/2fc90344-f7a9-11e5-9bfe-938469d21697.png)

#### Editar Mercadería

![captura de pantalla 2016-04-01 02 15 19](https://cloud.githubusercontent.com/assets/6784862/14198557/5ec1247e-f7a9-11e5-99c5-7199823384dc.png)

**Comment by carlosleite** [comment]
@mlored falta arreglar el titulo del modal y el campo :stock tiene que estar deshabilitado al editar.

**Comment by mlored** [comment]
Ok, voy a corregir eso!!

**Comment by mlored** [comment]
## ABM de Mercaderías

### Vistas

#### Listar Mercaderías

![captura de pantalla 2016-04-01 02 04 02](https://cloud.githubusercontent.com/assets/6784862/14198519/08d68388-f7a9-11e5-9343-fd3dc656d9fa.png)

#### Nueva Mercadería

![captura de pantalla 2016-04-01 16 11 53](https://cloud.githubusercontent.com/assets/6784862/14224281/7c464922-f865-11e5-8198-7485acbead00.png)

#### Editar Mercadería

![captura de pantalla 2016-04-01 23 54 40](https://cloud.githubusercontent.com/assets/6784862/14224283/8ff16eb6-f865-11e5-9202-7e28fad883f6.png)
