### ISSUE TITLE
Diseñar la vista Listar Movimientos de Cajas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#62]
En base a la descripción del issue #42 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by mlored** [comment]
## Movimientos de Cajas

### Vistas

#### Listar Movimiento de Cajas

![captura de pantalla 2016-04-04 10 11 24](https://cloud.githubusercontent.com/assets/6784862/14249279/097d283c-fa47-11e5-9de8-db86bb36a702.png)

#### Nuevo Movimiento de Caja

![captura de pantalla 2016-04-04 10 12 05](https://cloud.githubusercontent.com/assets/6784862/14251165/c0005f22-fa4f-11e5-848e-abb822cd7227.png)

#### Editar Movimiento de caja

![captura de pantalla 2016-04-04 10 13 47](https://cloud.githubusercontent.com/assets/6784862/14251195/d67a5686-fa4f-11e5-8bdb-02e058ed3969.png)

#### Mostrar Movimiento de Caja

![captura de pantalla 2016-04-04 10 12 49](https://cloud.githubusercontent.com/assets/6784862/14249364/67514db2-fa47-11e5-9bb7-98bf036cbab1.png)

**Comment by mlored** [comment]
@carlosleite @afaraldo @LudisM sugerencias u opiniones?

**Comment by carlosleite** [comment]
@mlored el listar debería ser un extracto creo y debe reflejar las diferentes monedas. Podes hacer una propuesta de como debe ser y lo vemos hoy.

**Comment by mlored** [comment]
## Movimientos de Cajas

### Vistas

#### Listar Movimientos de Cajas

##### Listado de Movimientos de Caja Registradora

![captura de pantalla 2016-04-05 19 47 44](https://cloud.githubusercontent.com/assets/6784862/14301834/0057548a-fb69-11e5-9166-d97f46cf8bca.png)

##### Listado de Movimientos de Caja Tarjeta

![captura de pantalla 2016-04-05 19 50 45](https://cloud.githubusercontent.com/assets/6784862/14301844/0dda0be8-fb69-11e5-9ef5-2aeaf6db4986.png)

#### Nuevo Movimiento de Caja

![captura de pantalla 2016-04-04 10 12 05](https://cloud.githubusercontent.com/assets/6784862/14251165/c0005f22-fa4f-11e5-848e-abb822cd7227.png)

#### Editar Movimiento de caja

![captura de pantalla 2016-04-04 10 13 47](https://cloud.githubusercontent.com/assets/6784862/14251195/d67a5686-fa4f-11e5-8bdb-02e058ed3969.png)

#### Mostrar Movimiento de Caja

![captura de pantalla 2016-04-04 10 12 49](https://cloud.githubusercontent.com/assets/6784862/14249364/67514db2-fa47-11e5-9bb7-98bf036cbab1.png)
