### ISSUE TITLE
Diseñar la vista Reporte de Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#63]
En base a la descripción del issue #45 diseñar las vistas:
- Listar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by LudisM** [comment]
### Reporte agrupado por dia

![reporte_agrupado_dia](https://cloud.githubusercontent.com/assets/3651168/14229182/b5f837b2-f8fa-11e5-8cb8-5144d9312dcf.png)

### Reporte agrupado por dia y resumido

![reporte_dia_reumido](https://cloud.githubusercontent.com/assets/3651168/14229186/cd16a654-f8fa-11e5-87bf-0e27423c2663.png)

### Reporte agrupado por mes y resumido

![reporte_mes_resumido](https://cloud.githubusercontent.com/assets/3651168/14229194/e329ac7a-f8fa-11e5-9cae-34371fb3de5e.png)

### Reporte agrupado por cliente

![agrupado-por-cliente](https://cloud.githubusercontent.com/assets/3651168/14229197/32d8d3b8-f8fb-11e5-9cee-6239aa118018.png)
