### ISSUE TITLE
Diseñar la vista Reporte de Movimientos de Caja

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#64]
En base a la descripción del issue #46 diseñar las vistas:
- Listar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by mlored** [comment]
## Reporte de Movimientos de Caja

### Vistas

#### Reporte agrupado por día

![captura de pantalla 2016-04-04 23 38 51](https://cloud.githubusercontent.com/assets/6784862/14270736/ffec0f04-fabe-11e5-8cc8-d25b11ce1470.png)

#### Reporte agrupado por dia y resumido

![captura de pantalla 2016-04-05 00 37 19](https://cloud.githubusercontent.com/assets/6784862/14271403/c153059c-fac6-11e5-8e04-028db0ed9e21.png)

#### Reporte agrupado por mes y resumido

![captura de pantalla 2016-04-05 00 12 20](https://cloud.githubusercontent.com/assets/6784862/14271109/48258be8-fac3-11e5-9d31-ad4976076ed5.png)
