### ISSUE TITLE
Diseñar la vista Reporte de Compras

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#65]
En base a la descripción del issue #44 diseñar las vistas:
- Listar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by carlosleite** [comment]
### Reporte agrupado por dia

![screenshot 2016-04-02 14 46 36](https://cloud.githubusercontent.com/assets/1580982/14228736/9fc5d4b2-f8ec-11e5-97b9-9553bfe56e5d.png)

### Reporte agrupado por dia y resumido

![screenshot 2016-04-02 15 25 57](https://cloud.githubusercontent.com/assets/1580982/14228737/9fd09e56-f8ec-11e5-8f7a-b603c721160e.png)

### Reporte agrupado por mes y resumido

![screenshot 2016-04-02 15 44 04](https://cloud.githubusercontent.com/assets/1580982/14228738/9fe96134-f8ec-11e5-973e-8f3250b7c516.png)

### Reporte agrupado por proveedor

![screen shot 2016-04-02 at 4 11 50 pm](https://cloud.githubusercontent.com/assets/1580982/14228777/c99aa118-f8ed-11e5-8bf6-924f93d5b7cd.png)

**Comment by carlosleite** [comment]
Hay un chart linear y otro con barras. Cual les parece mejor? o Area? 
Aca la libreria: http://morrisjs.github.io/morris.js/

**Comment by carlosleite** [comment]
Perdón, esa no va ser la libreria. Esta si: http://www.chartjs.org/

**Comment by afaraldo** [comment]
@carlosleite y depende, me gusta más el de barras, sin embargo pienso que si existen muchos datos a ser presentados quizás quede mejor el linear. Diría que el linear.

**Comment by carlosleite** [comment]
Asi es. Cuando la serie a agrupar es de tiempo como Día, mes y año podemos hacer linear. Y para proveedor en barras.
