### ISSUE TITLE
Diseñar la vista Reporte de Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#66]
En base a la descripción del issue #47  diseñar las vistas:
- Listar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by afaraldo** [comment]
**Reporte agrupado por dia**
![captura de pantalla de 2016-04-03 17 20 07](https://cloud.githubusercontent.com/assets/3640962/14235117/fbe9089e-fa05-11e5-88c3-dacea057e5d4.png)

**Reporte agrupado por dia y resumido**
![captura de pantalla de 2016-04-03 17 19 12](https://cloud.githubusercontent.com/assets/3640962/14235119/0d47e0e2-fa06-11e5-9d94-a990f89f5037.png)

**Reporte agrupado por mes y resumido**
![captura de pantalla de 2016-04-03 17 24 22](https://cloud.githubusercontent.com/assets/3640962/14235129/34dbf71a-fa06-11e5-9522-feb8c24f05ae.png)

Reporte agrupado por categoria
![captura de pantalla de 2016-04-03 17 35 01](https://cloud.githubusercontent.com/assets/3640962/14235138/6ddcdd68-fa06-11e5-9714-3c97c0c9b305.png)

**Comment by carlosleite** [comment]
@afaraldo en el Reporte agrupado por dia la columna de categoria debe ir antes que monto creo. Todo lo demas: :+1:

**Comment by afaraldo** [comment]
@carlosleite, corregido. Sí, así queda mejor.
