### ISSUE TITLE
Diseñar la vista Listar Movimientos de Cuenta Corriente

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#67]
En base a la descripción del issue #39 diseñar las vistas:
- Listar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by mlored** [comment]
## Movimientos de Cuenta Corriente

### Listado

![captura de pantalla 2016-04-05 10 15 14](https://cloud.githubusercontent.com/assets/6784862/14284936/a2db6428-fb17-11e5-9bb3-d33a3fa7dbc6.png)

**Comment by carlosleite** [comment]
@mlored 
- la columna para editar y eliminar no es necesario creo. 
- Arriba de los filtro se deberia indicar el nombre de la persona a la que corresponde la cuenta. Y una opcion para cambiarlo.

**Comment by mlored** [comment]
Genial! ahora arreglo eso!!

**Comment by mlored** [comment]
## Movimientos de Cuenta Corriente

### Listado de Cuenta Corriente de Proveedores

![captura de pantalla 2016-04-05 13 52 19](https://cloud.githubusercontent.com/assets/6784862/14295409/6ad70e48-fb43-11e5-8eab-79a0fd78dea3.png)

### Listado de Cuenta Corriente de Clientes

![captura de pantalla 2016-04-05 13 37 22](https://cloud.githubusercontent.com/assets/6784862/14295355/383ac9de-fb43-11e5-97b4-094525a6157d.png)

**Comment by mlored** [comment]
## Movimientos de Cuenta Corriente

### Listado de Cuenta Corriente de Proveedores

![captura de pantalla 2016-04-05 19 43 22](https://cloud.githubusercontent.com/assets/6784862/14301760/61047840-fb68-11e5-8a5c-62f56e5543a0.png)

### Listado de Cuenta Corriente de Clientes

![captura de pantalla 2016-04-05 19 44 34](https://cloud.githubusercontent.com/assets/6784862/14301770/74f9137e-fb68-11e5-8286-5db977a24d52.png)

**Comment by carlosleite** [comment]
Se actualizó el diseño ya que no era útil mostrar los filtros por tipo. Ademas se agrego el boton de imprimir.

![screenshot 2016-04-17 14 49 33](https://cloud.githubusercontent.com/assets/1580982/14589907/8da8f838-04bb-11e6-8053-d2e99a4e686f.png)
