### ISSUE TITLE
Diseñar el ABM de Proveedores

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#68]
En base a la descripción del issue #51  diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by afaraldo** [comment]
**Listado de proveedores**
![captura de pantalla de 2016-04-02 22 00 40](https://cloud.githubusercontent.com/assets/3640962/14230310/64f94000-f962-11e5-9132-1cadc671f6d6.png)

**Nuevo proveedor / editar proveedor**
![captura de pantalla de 2016-04-02 22 07 08](https://cloud.githubusercontent.com/assets/3640962/14230314/74ad4fbe-f962-11e5-84a9-8056e638bf2a.png)
