### ISSUE TITLE
Diseñar el ABM de Devolución de Compra/Venta

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#69]
En base a la descripción del issue #43  diseñar las vistas:
- Listar
- Nuevo 
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by LudisM** [comment]
### Listar devoluciones de compras

![lista_dev_compra](https://cloud.githubusercontent.com/assets/3651168/14235615/851db2c0-f9d1-11e5-86db-53788134a35e.png)

### Nueva devolucion de compra

![nueva_dev_compra](https://cloud.githubusercontent.com/assets/3651168/14235619/9a150fc0-f9d1-11e5-80cc-6b35315580c6.png)

### Editar devolucion de compra

![editar_dev_compra](https://cloud.githubusercontent.com/assets/3651168/14235625/a729f68a-f9d1-11e5-941a-b7a340797d8b.png)

### Listar devoluciones de ventas

![lista_dev_venta](https://cloud.githubusercontent.com/assets/3651168/14235631/bcc82fb6-f9d1-11e5-9f7d-6dbedd59e33b.png)

### Nueva devolucion de venta

![nueva_dev_venta](https://cloud.githubusercontent.com/assets/3651168/14235635/d3d972fa-f9d1-11e5-840a-6b9664fd3ab3.png)

### Editar devolucion de venta

![editar_dev_venta](https://cloud.githubusercontent.com/assets/3651168/14235638/debd54c0-f9d1-11e5-91f2-a5d1a374b7ac.png)
