### ISSUE TITLE
Diseñar el ABM de Usuarios

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#7]
Se requiere hacer el diseño para las vistas del ABM de Usuarios, esto incluye:
- Nuevo(y editar) usuario.
- Listar usuario.

**Comment by afaraldo** [comment]
Adjunto el diseño de vistas del ABM para Usuarios
![vista nuevo usuario](https://cloud.githubusercontent.com/assets/3640962/13573404/0ca08dec-e499-11e5-850d-01d91906959e.png)
![vista listar usuarios](https://cloud.githubusercontent.com/assets/3640962/13573405/0ca7ef42-e499-11e5-897f-4610f06b2c48.png)
![vista editar usuario](https://cloud.githubusercontent.com/assets/3640962/13573406/0cb0a812-e499-11e5-9b96-e5f5d0047c4c.png)

**Comment by louvelaz** [comment]
@afaraldo Faltaría el campo contraseña y correo tanto en Nuevo Usuario como en Editar Usuario.

**Comment by afaraldo** [comment]
Adjunto nueva imagen del diseño con los errores corregidos.
![vista nuevo usuario](https://cloud.githubusercontent.com/assets/3640962/13577113/56058616-e4aa-11e5-8654-f73bc92142e4.png)
![vista editar usuario](https://cloud.githubusercontent.com/assets/3640962/13577114/560b1978-e4aa-11e5-930a-54dd92da3885.png)

**Comment by louvelaz** [comment]
@afaraldo Quitar el campo Estado de ambos.

**Comment by afaraldo** [comment]
Corregido...

![configuraciones__nuevo_usuario 17](https://cloud.githubusercontent.com/assets/3640962/13589457/826589e4-e4f1-11e5-80dd-47b34992c02e.png)
![configuraciones__editar_usuario_ 1 18](https://cloud.githubusercontent.com/assets/3640962/13589459/8378f744-e4f1-11e5-89ef-377c0de095aa.png)
