### ISSUE TITLE
Implementar el feature Movimientos de Cta Cte

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#78]
En base a la descripción provista en el issue #39 y al diseño realizado en el issue #67 implementar el feature **Movimientos de Cta Cte**

**Comment by bordonwork** [comment]
@carlosleite te asigno esta tarea puesto que @LudisM esta indispuesta

**Comment by carlosleite** [comment]
Dale

**Comment by louvelaz** [comment]
@carlosleite @LudisM Cuando se selecciona un proveedor no muestra inmediatamente los movimientos

**Comment by carlosleite** [comment]
@louvelaz , te referis a que tarda mucho?

**Comment by louvelaz** [comment]
Cerre este issue el 21/04/2016
