### ISSUE TITLE
Actualizar el feature Movimientos de Mercaderías

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#79]
En base a la descripción provista en el issue #49 y al diseño realizado en el issue #60 implementar el feature **Movimientos de Mercaderías**

**Comment by louvelaz** [comment]
@LudisM 
- Cuando se aplica cualquier filtro, al dar clic en cualquier movimiento no se muestra el detalle
- El filtro por fecha no muestra los movimientos de hoy ni de ayer
- No se puede restaurar la lista sin ningún filtro cuando se aplica filtro por fecha, sin tener que recargar la pagina
- Cuando sale un mensaje de error de algún campo, el mensaje de advertencia de stock negativo no dice la mercadería

![mensj](https://cloud.githubusercontent.com/assets/6853236/14453712/642317f6-0064-11e6-9d4e-9698f893b2ac.jpg)
- En la documentación para el feature Movimientos de Mercaderías #85 se especifica que el sistema no debe dejar modificar el tipo de movimiento (ingreso|egreso) cuando se edita el mismo
- Cuando se hace un movimiento que genera stock negativo, el movimiento no produce ningún cambio en la cantidad de stock
