### ISSUE TITLE
Implementar el feature Categorías de Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#80]
En base a la descripción provista en el issue #41 y al diseño realizado en el issue #59 implementar el feature **Categorías de Gastos**

**Comment by louvelaz** [comment]
@mlored 
- En la barra de paginacion siempre se muestra pintada la pagina 1, aunque no se este mostrando esa pagina 

![pag](https://cloud.githubusercontent.com/assets/6853236/14420057/d44b40e4-ff97-11e5-80cc-5a668df7ac46.jpg)
- En la documentación para el feature Categorías de Gastos #41 se especifica que se deben mostrar las ultimas 25 categorías, no solo 10 categorías.
