### ISSUE TITLE
Implementar el feature Movimientos de Caja

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#81]
En base a la descripción provista en el issue #42 y al diseño realizado en el issue #35 implementar el feature turnos

**Comment by bordonwork** [comment]
@mlored cómo vas con este issue?

**Comment by mlored** [comment]
Qué hiciste ayer: Modificar el limite del campo en el modelo de
caja_extractos y  logica para los extractos  #81 Implementar feature de
Movimientos de Cajas
<https://github.com/afaraldo/casa-de-las-pinturas/issues/81>
Qué harás hoy: Hoy no podre trabajar, recuperaré las horas mañana
Qué problemas tuviste: Ninguno

2016-04-21 8:47 GMT-04:00 Rubén Bordón <notifications@github.com>:

**Comment by mlored** [comment]
@bordonwork  Me falta concluir la parte de extractos de caja y balance

**Comment by bordonwork** [comment]
@mlored como vamos?

**Comment by louvelaz** [comment]
Moví a To Review este issue el 29/04/2016

**Comment by louvelaz** [comment]
@mlored 
- Se pueden usar Categorías de gastos que ya fueron previamente eliminadas y no debería
- Se pueden borrar Categorías de gastos que fueron usadas en Movimiento de Caja y no debería
- Cuando se ingresa Monto "0" (cero) sale la advertencia pero no el mensaje que indica que se debe introducir un monto mayor a 0

![msj](https://cloud.githubusercontent.com/assets/6853236/14911049/940dbf5c-0dc0-11e6-836a-64ee886f40b8.jpg)

**Comment by bordonwork** [comment]
@mlored que pasa con este issue que no lo pones a done?

**Comment by mlored** [comment]
@bordonwork  tenia 3 errores que corregir, 2 ya estan corregidos, que lo hice el viernes, solo que quedo pendiente que cuando se ingresa Monto "0" (cero) sale la advertencia pero no el mensaje que indica que se debe introducir un monto mayor a 0. Esta tarde estuve retomando el trabajo, y lo estoy corrigiendo.

**Comment by bordonwork** [comment]
Entiendo, dale prioridad a esta tarea puesto que pertenece al Sprint 4

**Comment by mlored** [comment]
Bueno gracias!!
