### ISSUE TITLE
Implementar el feature Compras (Crédito)

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#82]
En base a la descripción provista en el issue #35 y al diseño realizado en el issue #56 implementar el feature **Compras Crédito**

**Comment by carlosleite** [comment]
@louvelaz , hay un bug pendiente en este feature. Al cambiar un proveedor al editar la compra las cuentas corrientes no se actualizan correctamente. @afaraldo esta trabajando en eso. Todo lo demas esta hecho

**Comment by louvelaz** [comment]
@carlosleite Ok

**Comment by louvelaz** [comment]
@afaraldo 
- El calendario de Fecha de vencimiento no se ve completo

![completo](https://cloud.githubusercontent.com/assets/6853236/14627808/df2ace60-05c5-11e6-8031-8aafbbb5a0b5.jpg)
- El Número de Comprobante debería ser un valor único
- Se desarregla este campo cuando sale un mensaje de error, y se repite el mensaje dos veces

![sale](https://cloud.githubusercontent.com/assets/6853236/14627809/ee2be34a-05c5-11e6-9aa9-0806b6619202.jpg)
- Cuando se imprime, el campo Numero de Compra no solo sale el numero:

![imprimir](https://cloud.githubusercontent.com/assets/6853236/14627811/f9c7aa54-05c5-11e6-9b97-563d0cb9c291.jpg)
- La pestaña Crédito Utilizado en la Vista del detalle de la compra no funciona

![cre](https://cloud.githubusercontent.com/assets/6853236/14629220/fc10eaa2-05d2-11e6-9289-b4dc823c684f.jpg)
- El filtro por "Nro de compra o Nro de comprobante" no busca por Nro de comprobante
- Cuando el nombre de un proveedor es largo, el campo se encima con el botón "Contado"

![proveedor](https://cloud.githubusercontent.com/assets/6853236/14629560/973b8d28-05d5-11e6-8927-542038d8c17a.jpg)

**Comment by bordonwork** [comment]
@afaraldo cómo vas con este issue?

**Comment by afaraldo** [comment]
@bordonwork aún me falta para terminarlo, estoy con otros trabajos de la facu también, pero esta noche/madrugada haré todo lo posible para que pueda ser cerrado.

**Comment by bordonwork** [comment]
@afaraldo  entiendo, sin problema.

**Comment by louvelaz** [comment]
Issue cerrado el día 24/04/16
