### ISSUE TITLE
Actualizar el feature Usuarios

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#83]
En base a las políticas especificadas en el issue #31  y al diseño realizado en el issue #7 actualizar el feature Usuarios

**Comment by carlosleite** [comment]
Nuevas credenciales: user: admin, pass: Admin+123

**Comment by louvelaz** [comment]
@afaraldo No se puede editar los datos del superusuario "admin", incluyendo su contraseña, muestra este mensaje

![error](https://cloud.githubusercontent.com/assets/6853236/14421646/c74132a6-ffa0-11e5-8f50-932c9aba1c46.jpg)
