### ISSUE TITLE
Implementar el feature Pagos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#84]
En base a la descripción provista en el issue #40 y al diseño realizado en el issue #57 implementar el feature **Pagos**

**Comment by louvelaz** [comment]
@carlosleite 
-  El mensaje debería decir que el campo es obligatorio:

![mensaje](https://cloud.githubusercontent.com/assets/6853236/14630283/86a69b6a-05da-11e6-842b-3dae374da350.jpg)
- El filtro por "Nro de pago o Nro de comprobante" no busca por Nro de comprobante
- Cuando se edita el Pago o cuando sale el mensaje de fondo negativo de la caja, si se va a pagar con 2 monedas distintas, el monto en guaranies cambia por el monto total a pagar 
- El diseño del detalle de pago es ligeramente diferente al formulario.

**Comment by carlosleite** [comment]
@louvelaz , con respecto al diseño lo cambiamos porque hay solo una forma de pago y siempre van a haber solo 3 o 4 monedas; por lo tanto no es necesario que el usuario seleccione las formas(siempre efectivo) y monedas de pago(son pocas y no quita mucho espacio).

Queda pendiente actualizar el issue de diseño.

**Comment by louvelaz** [comment]
@carlosleite Ok

**Comment by louvelaz** [comment]
Cerre este issue el 21/04/2016

**Comment by LudisM** [comment]
@bordonwork  este commit es del issue #89
