### ISSUE TITLE
Implementar el feature Compras (Contado)

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#86]
En base a la descripción provista en el issue #35 y al diseño realizado en el issue #56 implementar el feature **Compras Contado**

**Comment by louvelaz** [comment]
@afaraldo 
- Output de rails_best_practices
  ![compras 2](https://cloud.githubusercontent.com/assets/6853236/15091816/f6f20606-1422-11e6-83b5-757d621f9355.jpg)
  ![compras 3](https://cloud.githubusercontent.com/assets/6853236/15091817/f6f3e340-1422-11e6-910e-60b111301637.jpg)
  ![compras 4](https://cloud.githubusercontent.com/assets/6853236/15091818/f6f762f4-1422-11e6-937d-f8527ea09564.jpg)
  ![compras 5](https://cloud.githubusercontent.com/assets/6853236/15091819/f6faca8e-1422-11e6-89d0-f5bb2d488b86.jpg)
  ![compras](https://cloud.githubusercontent.com/assets/6853236/15091820/f700f382-1422-11e6-8bd7-fe9fd0e5c6f3.jpg)
- En Editar Compra: Cuando se edita la parte de Forma de Pago de una compra, esta no se actualiza.

**Comment by bordonwork** [comment]
@carlosleite dado el tiempo y la prioridad de esta tarea, decidimos asignartela. Adrian va a explicarte bienj lo que se requiere hacer. Esta tarea debe ser tu prioridad.

**Comment by louvelaz** [comment]
@carlosleite 
- Cuando el Nro. de Comprobante es largo, en el show se encima con el campo Estado
  ![comp2](https://cloud.githubusercontent.com/assets/6853236/15244911/933a336e-18d1-11e6-9161-00b5613b1532.jpg)
- Cuando se edita una Compra y se cambia la Condición de crédito a contado, ya no aparece la grilla de Formas de pago para añadir los montos
- Cuando se crea una nueva Compra y sale la advertencia de existencia negativa de stock, si se decide cambiar la Condición de crédito a contado, ya no aparece la grilla de Formas de pago para añadir los montos
- Cuando se crea una Compra y en el campo Cantidad se ingresa mas de 9 dígitos, tira error de rails. Creo que se debe a que cuando se ingresa una cantidad así, al multiplicar por el importe total, este sobrepasa el limite superior
  ![error](https://cloud.githubusercontent.com/assets/6853236/15245578/6ac2b448-18d5-11e6-8fde-8d49c44c3e10.jpg)

**Comment by louvelaz** [comment]
@carlosleite 
El Editar esta bastante inestable. 
- En Editar: Cuando se escribe un monto mayor al total, tira error de rails
- En Editar: Cuando se agrega o quita mercaderías, tira error de rails
- En Editar: Cuando se edita la cantidad y el monto a pagar, tira error de rails
- En Editar: Cuando sale el mensaje de stock negativo, se resetea la Forma de pago 
- En New: Cuando sale el mensaje de disponibilidad negativa en la moneda, se resetea la Forma de pago

**Comment by louvelaz** [comment]
@carlosleite 
- En Editar: Si se quita mercaderías, sale el mensaje "Importe y cantidades no se puede editar. Posee pagos asociados" Pero igualmente se elimina la mercadería, el importe y el monto a pagar se desestabilizan, en Importe queda registrado el importe sin la mercadería eliminada, y en Monto a pagar queda registrado el monto como si no se hubiera eliminado la mercadería.
  ![comp](https://cloud.githubusercontent.com/assets/6853236/15632621/af2d05c8-2566-11e6-88e4-0d4cd32df755.jpg)
  ![comp2](https://cloud.githubusercontent.com/assets/6853236/15632622/af335e1e-2566-11e6-9c20-cbf9796759a1.jpg)
