### ISSUE TITLE
Implementar el feature Ventas (Crédito)

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#87]
En base a la descripción provista en el issue #37, a las políticas definidas en el issue #33  y al diseño realizado en el issue #55 implementar el feature **Ventas Crédito**

**Comment by louvelaz** [comment]
Moví a To Review este issue el 24/04/2016

**Comment by louvelaz** [comment]
@carlosleite 
- El botón Guardar debería decir: Guardar Venta

![venta](https://cloud.githubusercontent.com/assets/6853236/14772318/e95283de-0a6a-11e6-98c8-e7cbf0a91e6d.jpg)
- Cuando se muestra el detalle de una venta, debería decir Venta Nro. x 

![venta 2](https://cloud.githubusercontent.com/assets/6853236/14772326/fc9e0fc6-0a6a-11e6-9345-b72cdab7183c.jpg)
- En la grilla debería decir: Número de venta y Cliente

![venta 3](https://cloud.githubusercontent.com/assets/6853236/14772331/0cedcd62-0a6b-11e6-91d7-2b8aed4ae510.jpg)
- El filtro por nro de Venta debería decir: Nro de Venta

![venta 4](https://cloud.githubusercontent.com/assets/6853236/14772343/19b6e2a4-0a6b-11e6-99ab-8facc7837e88.jpg)
- El filtro por "Nro de Venta o Nro de Comprobante" no funciona
- El botón Cancelar del mensaje de stock negativo redirige al listado de compras no al de ventas

![neg](https://cloud.githubusercontent.com/assets/6853236/14772353/3c227f92-0a6b-11e6-9988-e12905dc007a.jpg)
- Si se edita el precio unitario de una mercaderia y se produce stock negativo, cuando sale el mensaje de stock negativo el precio unitario se resetea al precio original

**Comment by louvelaz** [comment]
Issue cerrado el día 27/04/16
