### ISSUE TITLE
Implementar el feature Devolución Compra

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#89]
En base a la descripción provista en el issue #43 y al diseño realizado en el issue #69 implementar el feature **Devolución Compras**

**Comment by LudisM** [comment]
Tiempo del ultimo commit 03h:30m

**Comment by LudisM** [comment]
tiempo del ultimo commit 02 h

**Comment by louvelaz** [comment]
@LudisM 
- Cuando no se ingresa nada en el campo "Compra", sale la advertencia pero no el mensaje que indica que se debe introducir un compra, o en el caso que no haya compras asociadas con ese proveedor debe decir que no hay compras de ese proveedor
  ![msj](https://cloud.githubusercontent.com/assets/6853236/15234509/749c8408-1880-11e6-8365-f7ed424d3f86.jpg)
- En el campo Motivo se debe poner un \* para indicar que es un campo requerido
  ![ob](https://cloud.githubusercontent.com/assets/6853236/15234515/7e8f86c2-1880-11e6-97ba-35e7e6cb1be4.jpg)
- Cuando se agrega una nueva devolución, se debería mostrar el Total del monto de la devolución 
  ![sumar](https://cloud.githubusercontent.com/assets/6853236/15235068/3285a210-1886-11e6-94de-b46145b0aef7.jpg)
- Cuando sale la advertencia "cantidad mayor al de la boleta" en el detalle de la devolución, se resetea el campo Compra
  ![no 2](https://cloud.githubusercontent.com/assets/6853236/15235521/17aa86b4-188a-11e6-9366-c46ab9f40b8c.jpg)

**Comment by louvelaz** [comment]
@LudisM 
- En Editar: Cuando una Devolución tiene varias mercaderías, si al editar se quita una mercadería, no se actualiza ni el total ni las mercaderías y queda como si no se hubiera quitado ninguna mercadería

**Comment by louvelaz** [comment]
@LudisM 
- Cuando una compra que tiene asociada una devolución se elimina, al entrar en esa devolución tira error de rails
- Cuando una Devolución tiene varias mercaderías, si se quita una mercadería y al guardar sale el mensaje de stock negativo, la mercaderia eliminada vuelve a aparecer
