### ISSUE TITLE
Realizar ABM de Proveedores

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#9]
Depende del issue #8 y #10 
Diseño de la vista nuevo/editar
![image](https://cloud.githubusercontent.com/assets/3639650/13547597/0011b8fe-e2b8-11e5-8316-dcd8b00eb6cf.png)
En base al diseño del issue #10 y al proveído se requiere generar el ABM para el modelo Proveedores. Esto incluye:
- [x] Agregar un proveedor.
- [x] Editar un proveedor.
- [x] Eliminar un proveedor(borrado ocioso).
- [x] Listar proveedores.
- [x] Agregar validación les lado del cliente y servidor

Los formularios deben estar validados. Ver [jquery-validation](https://github.com/jzaefferer/jquery-validation)

**Comment by louvelaz** [comment]
@carlosleite En Listar Proveedores hay una columna que no posee titulo.
![screenshot_1](https://cloud.githubusercontent.com/assets/6853236/13594022/9e2d9782-e4df-11e5-90e1-cc19ea0ffd27.jpg)
- Se guardan caracteres no numéricos en el campo teléfono y no debería.
- Se guardan dos proveedores con el mismo nombre.
- En el campo dirección y teléfono no debería aceptar 1 solo carácter.
- En el campo limite de crédito no parece tener limite final y se muestra así: 
  ![resultado](https://cloud.githubusercontent.com/assets/6853236/13594095/4a2b8346-e4e0-11e5-9750-abd8f337ecf9.jpg)

**Comment by carlosleite** [comment]
Gracias. Lo voy a revisar.

**Comment by carlosleite** [comment]
@louvelaz, Algunas observaciones:
- La columna que no tiene titulo es la de los botones de "movimientos". No debe tener titulo.
- El campo de telefono acepta caracteres no numericos ya que se pueden dar los casos como: "(021) 344-3333", "0985 555 555", "021-232323, 071-333333", "Gerente: 0923-233234, Vendedor: 0988-3434334"
- Para todos los campos que esten presentes se tiene un minimo de 2 caracteres de longitud.
- Se actualizaron los siguientes limites maximos: nombre(150), telefono(50), direccion(150), numero_documento(50). Queda pendiente actualizar la documentacion.
- Tambien se agrego la columna de RUC/CI a la tabla.
