### ISSUE TITLE
Implementar el feature Reporte de Compras

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#90]
En base a la documentación provista en el issue #35 y al diseño provisto en el issue #65 realizar la vista para **Reporte de Compra**.

**Comment by bordonwork** [comment]
@carlosleite completa la estimación del issue para poder hacer la evaluación de tu estimativa.

**Comment by louvelaz** [comment]
Moví a To Review este issue el 28/04/2016

**Comment by louvelaz** [comment]
@carlosleite 
- Para el modo resumido del reporte agrupado por proveedor, ver alguna solución para los nombres de proveedor que son muy largos, ya que no se ven por completo. Sugeriría poner algún tipo de referencia

![rep](https://cloud.githubusercontent.com/assets/6853236/14906983/504eca52-0d90-11e6-898c-3c68878983f4.jpg)

Sugerencia:
- Para el grafico del modo resumido del reporte agrupado por proveedor, estaria bueno no hacerle por orden alfabetico sino por montos, por orden decreciente o creciente, para que asi se pueda hacer un comparativo logico de quienes son los principales proveedores

**Comment by carlosleite** [comment]
Se invirtió la posicion de las series para el caso de agrupado por proveedor. En el eje y aparecen los proveedores y en el eje x los totales.

Tambien ahora en el modo resumido se puede ordenar los datos haciendo click en la cabezera de las columnas.
