### ISSUE TITLE
Implementar el feature Historico de Mercaderias

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#91]
Corresponde a la documentación del issue #49. Se cambia de nombre para no confundir con ABM de movimientos de mercadería.

**Comment by carlosleite** [comment]
La opcion en el menu: Stock>Historico de mercaderias
Tambien en el inventario hay un boton "Movimientos" para cada mercaderia

**Comment by louvelaz** [comment]
@carlosleite 
- Cuando se intenta ver el detalle de un movimiento, específicamente los de Movimiento de mercadería, tira este error de rails. No ocurre esto con movimientos generados por compra o venta. Creo que la ruta esta mal escrita.

![msj](https://cloud.githubusercontent.com/assets/6853236/14993193/a94593de-1137-11e6-9a85-9552b7b627e8.jpg)
