### ISSUE TITLE
Implementar el feature Reporte de Gastos

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#93]
En base a la documentación provista en el issue #41 y al diseño provisto en el issue #66 realizar la vista para Reporte de Gastos.

**Comment by louvelaz** [comment]
@carlosleite 
- Cuando se quiere filtrar por fecha en "Últimos 30 días" tira un error en la consola

![error](https://cloud.githubusercontent.com/assets/6853236/15091300/f03e52f2-1412-11e6-8ff9-65a1ba116189.jpg)
- Output de rails_best_practices
  ![rep gastos 2](https://cloud.githubusercontent.com/assets/6853236/15091293/af7a0dec-1412-11e6-80b0-bbdfbfa88457.jpg)
  ![rep gastos 3](https://cloud.githubusercontent.com/assets/6853236/15091294/af7c562e-1412-11e6-890c-509ae0ffb525.jpg)
  ![rep gastos 4](https://cloud.githubusercontent.com/assets/6853236/15091295/af825c18-1412-11e6-9906-94a9feb9fabc.jpg)
  ![rep gastos](https://cloud.githubusercontent.com/assets/6853236/15091296/af827568-1412-11e6-8e12-9247220cf178.jpg)
