### ISSUE TITLE
Implementar el feature Devolución de Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#94]
En base a la documentación provista en el issue #43 y al diseño provisto en el issue #69 realizar la vista para **Devolución de Ventas**.

**Comment by louvelaz** [comment]
@LudisM 
- En el listado de devoluciones, debe decir Clientes en el filtro de buscar por clientes y el titulo "ventas" la primera letra debe estar con mayúscula
  ![may y cliente](https://cloud.githubusercontent.com/assets/6853236/15235295/025a92e2-1888-11e6-8a0a-1d7685ba5bef.jpg)
- En el new de Devolución, debe decir Cliente en vez del campo proveedor
  ![cli](https://cloud.githubusercontent.com/assets/6853236/15235306/19e76cf0-1888-11e6-84f6-ed245c86bc35.jpg)
- El mensaje de error del campo Venta debe estar en color rojo, no gris
  ![rojo](https://cloud.githubusercontent.com/assets/6853236/15235319/31aaedc6-1888-11e6-8404-7ae66eb15f58.jpg)
- En el campo Motivo se debe poner un \* para indicar que es un campo requerido
  ![ob](https://cloud.githubusercontent.com/assets/6853236/15235333/46e77376-1888-11e6-8ee3-9d16831485a0.jpg)
- Cuando sale la advertencia "cantidad mayor al de la boleta" en el detalle de la devolución, se resetea el campo Venta
  ![no](https://cloud.githubusercontent.com/assets/6853236/15235426/385c6dc4-1889-11e6-83c5-a00ba5f2a08b.jpg)
- Cuando se agrega una nueva devolución, se debería mostrar el Total del monto de la devolución 
  ![sumar 2](https://cloud.githubusercontent.com/assets/6853236/15235546/65141c30-188a-11e6-9a31-468abd0dd5e6.jpg)

**Comment by louvelaz** [comment]
@LudisM 
- En Editar: Cuando una Devolución tiene varias mercaderías, si al editar se quita una mercadería, no se actualiza ni el total ni las mercaderías y queda como si no se hubiera quitado ninguna mercadería
- En el listado de devoluciones, el campo "cliente" la primera letra debe estar con mayúscula
  ![may](https://cloud.githubusercontent.com/assets/6853236/15386768/94da16e4-1d77-11e6-88e2-ad43ba15df77.jpg)

**Comment by louvelaz** [comment]
@LudisM 
- No se puede editar ninguna devolución, tira error de rails
- Cuando una venta que tiene asociada una devolución se elimina, al entrar en esa devolución tira error de rails

**Comment by louvelaz** [comment]
@LudisM 
- Se pueden eliminar y editar devoluciones que ya fueron utilizadas en ventas o cobros
