### ISSUE TITLE
Implementar el feature Ventas (Contado)

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#95]
En base a la documentación provista en el issue #33 y al diseño provisto en el issue #55 realizar la vista para **Ventas Contado**.

**Comment by louvelaz** [comment]
@afaraldo 
- Cuando el Nro. de Comprobante es largo, en el show se encima con el campo Estado
  ![comp](https://cloud.githubusercontent.com/assets/6853236/15243842/24c60200-18cc-11e6-91f2-781fd29839be.jpg)
- Cuando se edita una Venta y se cambia la Condición de crédito a contado, ya no aparece la grilla de Formas de pago para añadir los montos
- Cuando se crea una nueva venta y sale la advertencia de existencia negativa de stock, si se decide cambiar la Condición de crédito a contado, ya no aparece la grilla de Formas de pago para añadir los montos
- Cuando se crea una Venta y en el campo Cantidad se ingresa mas de 9 dígitos, tira error de rails. Creo que se debe a que cuando se ingresa una cantidad así, al multiplicar por el importe total, este sobrepasa el limite superior
  ![error](https://cloud.githubusercontent.com/assets/6853236/15245167/fcd9086c-18d2-11e6-90fd-d51129e187c7.jpg)

**Comment by louvelaz** [comment]
@afaraldo 
El Editar esta bastante inestable.
- En Editar: Cuando se escribe un monto mayor al total, tira error de rails
- En Editar: Cuando se agrega o quita mercaderías, tira error de rails
- En Editar: Cuando se edita la cantidad y el monto a pagar, tira error de rails
- En Editar: Cuando sale el mensaje de stock negativo, se resetea la Forma de pago

**Comment by louvelaz** [comment]
@afaraldo 
- En Editar: Si se quita mercaderías, sale el mensaje "Importe y cantidades no se puede editar. Posee pagos asociados" Pero igualmente se elimina la mercadería, el importe y el monto a pagar se desestabilizan, en Importe queda registrado el importe sin la mercadería eliminada, y en Monto a pagar queda registrado el monto como si no se hubiera eliminado la mercadería. 
  ![mer](https://cloud.githubusercontent.com/assets/6853236/15632551/fe4c7be6-2563-11e6-8a5c-b443526c5c41.jpg)
  ![mer2](https://cloud.githubusercontent.com/assets/6853236/15632552/fe4fdbba-2563-11e6-9705-159c4ec1e50e.jpg)
