### ISSUE TITLE
Implementar Efectivizar

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#96]
En base a la documentación provista en el issue #42 realizar el feature **Efectivizar**.

**Comment by louvelaz** [comment]
@afaraldo 
- No se puede seleccionar una Fecha. Tira error en la consola y salen 2 calendarios
  ![error](https://cloud.githubusercontent.com/assets/6853236/15389184/a34a46f2-1d83-11e6-9c5a-9b284f8925ba.jpg)

![calen](https://cloud.githubusercontent.com/assets/6853236/15389193/ad364ce2-1d83-11e6-8257-1d2d256e48fe.jpg)

**Comment by louvelaz** [comment]
@afaraldo 
- Cuando se utiliza el filtro "Tarjeta", el show de los movimientos "Transferencia de cuenta bancaria a caja registradora" tira error de rails
  ![error](https://cloud.githubusercontent.com/assets/6853236/15631193/f6c400a4-2529-11e6-9649-8e2f8900ebcf.jpg)
  ![error2](https://cloud.githubusercontent.com/assets/6853236/15631194/f7db5bd6-2529-11e6-9b2c-9b1257079cdf.jpg)
- A pesar que sale el mensaje indicando que la disponibilidad de la moneda va a quedar negativa, se guarda el monto en la bd
- Cuando se ingresa una cantidad con 13 dígitos en el "Monto", tira este error en la consola
  ![error 1000](https://cloud.githubusercontent.com/assets/6853236/15631198/0a98f38c-252a-11e6-84f1-030cf4cf86bf.jpg)

**Comment by afaraldo** [comment]
Hello @louvelaz, el último error  _"Cuando se ingresa una cantidad con 13 dígitos en el "Monto", tira este error en la consola"_ no lo pude reproducir. Podrías decirme que datos introdujiste para saltará el error.

Yo intenté de la siguiente forma:
![captura de pantalla de 2016-06-06 02 36 05](https://cloud.githubusercontent.com/assets/3640962/15813985/44b21f0e-2b91-11e6-979a-22c48bffcb3c.png)

**Comment by louvelaz** [comment]
@afaraldo Esta es la prueba que hice
![err](https://cloud.githubusercontent.com/assets/6853236/15840704/9bebb126-2c19-11e6-9481-99ed02580e5f.jpg)

**Comment by louvelaz** [comment]
@afaraldo 
- En Editar: el campo "Tipo" no debería poder ser editable
