### ISSUE TITLE
Implementar el feature Reporte de Ventas

### ISSUE THREAD

**Issue by bordonwork** [afaraldo/casa-de-las-pinturas#98]
En base a la documentación provista en el issue #45 y al diseño provisto en el issue #63 realizar la vista para **Reportes de Ventas**.

**Comment by louvelaz** [comment]
@mlored 
- Output de rails_best_practices
  ![rep venta 2](https://cloud.githubusercontent.com/assets/6853236/15091242/e76e62fe-1410-11e6-9f8e-4b76173a9bc3.jpg)
  ![rep venta 3](https://cloud.githubusercontent.com/assets/6853236/15091243/e7713056-1410-11e6-8d2a-ae74d0b1638d.jpg)
  ![rep venta 4](https://cloud.githubusercontent.com/assets/6853236/15091244/e7759d58-1410-11e6-9519-79cac522dbeb.jpg)
  ![rep venta](https://cloud.githubusercontent.com/assets/6853236/15091245/e777a4e0-1410-11e6-9b3a-fafaa78e778d.jpg)
- No se encontraron otros bugs

**Comment by bordonwork** [comment]
@mlored falto tu commit

**Comment by mlored** [comment]
@bordonwork no fallo, lo que paso es que no hice referencia a este feature, por eso nomas figura la referencia del feature de movimiento para stock inicial, en la cual se encuentra el commit que se realizo de este feature
